### ISSUE TITLE
Email address being used instead of password filename

### ISSUE THREAD

**Issue by braderhart** [browserpass/browserpass-extension#100]
### General information
-   Operating system + version: Arch 5.0.7-arch1-1
-   Browser + version: Chromium 73.0.3683.103
-   Information about the host app: 
    -   How did you install it? Package manager
    -   If installed an official release, put a version (`$ browserpass --version`): 3.0.6
-   Information about the browser extension:
    -   How did you install it? Package manager
    -   Browserpass extension version as reported by your browser: 3.0.9

---
### Exact steps to reproduce the problem
1. Use browserpass on a domain with an `email` field in the password file
2. Password filename matches username to be used

### What should happen?
- Password filename should be used as username

### What happened instead?
- Email address is populated in username field

### Recommendation
- If using email address as username, require it use `login` or `username` fields or be the name of the password file

**Comment by erayd** [comment]
@maximbaz What do you think? I don't have a strong opinion either way.

**Comment by erayd** [comment]
@braderhart We've decided to remove 'email' from the list of fields considered to be a username. Stand by.
