### ISSUE TITLE
Extension logo in browser looks like a question mark

### ISSUE THREAD

**Issue by braderhart** [browserpass/browserpass-extension#101]
### General information
-   Operating system + version: Arch 5.0.7-arch1-1
-   Browser + version: Chromium 73.0.3683.103
-   Information about the host app: 
    -   How did you install it? Package manager
    -   If installed an official release, put a version (`$ browserpass --version`): 3.0.6
-   Information about the browser extension:
    -   How did you install it? Package manager
    -   Browserpass extension version as reported by your browser: 3.0.9

---
### Exact steps to reproduce the problem
1. Install browserpass extension
2. Look at extension logo in browser

### What should happen?
- Logo could be rotated horizontally and would be more distinct and less confusing

### What happened instead?
- Logo looks like a question mark depending on size

**Comment by erayd** [comment]
@braderhart Thanks. We've already agonised over this during the logo design phase, and a number of changes were made to reduce its question-mark-likeness. The current orientation is deliberate and will not change.

The feedback is useful, but we do not currently have any intention to change the logo further (and thereby compromise the design), particularly as this only appears to still be an issue on lower-dpi screens at very small sizes.

**Comment by braderhart** [comment]
Thanks and understood.
