### ISSUE TITLE
Browserpass is awesome

### ISSUE THREAD

**Issue by DamienCassou** [browserpass/browserpass-extension#104]
I just would like to say that browserpass is an awesome extension. I use browserpass 20 times per day. I love it. Thank you so much to everyone who made this possible.

**Great job**

**Comment by erayd** [comment]
Thanks! Glad you like it :-).

**Comment by TychoSchenkeveld** [comment]
Me too! I use it many more times per day than 20 :)

**Comment by Loki-Afro** [comment]
Just wanted to open a similar issue :D
