### ISSUE TITLE
TypeError: settings.hostError.params is undefined

### ISSUE THREAD

**Issue by Darkitty** [browserpass/browserpass-extension#113]
### General information

-   Operating system + version: Arch
-   Browser + version: Firefox 66.0.3 x64
-   Information about the host app:
    -   How did you install it? pacman for browserpass
        
    -   If installed an official release, put a version (`$ browserpass --version`): Browserpass host app version: 2.0.21
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it? package manager (download from mirror)
        
    -   Browserpass extension version as reported by your browser: 3.0.10

---

If you are seeing "Error: Specified native messaging host not found", have you followed [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

---

### Exact steps to reproduce the problem

1. Run Firefox

2. Click on the extension

### What should happen?

Show password

### What happened instead?

```TypeError: settings.hostError.params is undefined```

And I got this from the browser console :

```stderr output from native app com.github.browserpass.native: [Browserpass] 2019/04/15 01:17:11 Invalid action```

**Comment by maximbaz** [comment]
You need to update your native host app, in fact there are `browserpass` and `browserpass-firefox` in Arch Linux [community] repos 😉

**Comment by Darkitty** [comment]
Ok, I will update. Maybe the mirror use old version. Thanks :)

**Comment by maximbaz** [comment]
Enjoy, and let me know if you stumble upon some other issue in the process 😉

**Comment by Darkitty** [comment]
Perfect. Good job :). I can't use pacman but I download from the package page and work good. Really good job <3.
