### ISSUE TITLE
Sorting order in new version inconsistent

### ISSUE THREAD

**Issue by TychoSchenkeveld** [browserpass/browserpass-extension#114]
### General information

-   Operating system + version: MacOS 10.14.4
-   Browser + version: Firefox and Chrome
-   Browserpass version 3.0.10

### Exact steps to reproduce the problem

1. I have 2 logons for the same site. One is called ADM, one is SESA. The site is identified by the folder name, inside I have 2 files for the 2 different accounts.

2. ADM is at the top, SESA at the bottom (alphabetically sorted?). Now log in with SESA.

3. Next time, SESA is at the top. If I used ADM that will be at the top again.

### What should happen?

It would be great if the sort order was fixed (e.g. aphabetically) so that my "muscle memory" doesn't get confused between these two :)

In Browserpass 2.x these were fixed so it wasn't an issue. I understand some smart sorting is used but perhaps it could be a toggle on/off?
### What happened instead?

They keep shuffling around as I use them

**Comment by erayd** [comment]
@TychoSchenkeveld We'd prefer not to add an option for this, as we're trying to keep the number of options minimal. This helps prevent regressions that may cause problems when things change, especially if the option is something that neither I nor @maximbaz will use (so we're less likely to notice problems with it).

If the main issue is muscle memory, something that can help with that is to incorporate a search character into your memorised key combo. Noting you're only choosing between two entries, a single character should be enough to promote your preferred entry to the top of the list.

**Comment by maximbaz** [comment]
Make sure to check [this section](https://github.com/browserpass/browserpass-extension#password-matching-and-sorting) for details on the sorting algorithm 🙂 

It was designed to deliver the most expected results, I highly recommend you to give it a longer try. @erayd's suggestion is what I'm using myself and it works really well, you hit "Ctrl+Shift+L" to open popup, then you think of logging in via "SESA" so you press "s" and hit Enter.

**Comment by TychoSchenkeveld** [comment]
Thanks for the quick replies! Yes good point about using the keyboard more. And it is indeed also a case of not being used to it. I'm using browserpass a lot (especially because I have multiple accounts at work and I change my passwords often to long complex strings). Thanks very much for the great work on it! And sorry for logging many issues :)

**Comment by maximbaz** [comment]
We highly appreciate the feedback!

**Comment by erayd** [comment]
> And sorry for logging many issues :)

No need to apologise for that - logging issues helps us improve things :+1:
