### ISSUE TITLE
CRX File Extension Disabled Automatically

### ISSUE THREAD

**Issue by larry-beck** [browserpass/browserpass-extension#119]
When I drag and drop the crx file for webstore into Chromium, it installs but the extension is disabled and it says it is not available in the webstore, see below.

This extension is not listed in the Chrome Web Store and may have been added without your knowledge.

**Comment by erayd** [comment]
> This extension is not listed in the Chrome Web Store and may have been added without your knowledge.

This extension is definitely [listed in the webstore](https://chrome.google.com/webstore/detail/browserpass/naepdomgkenhinolocfifgehidddafch), and it's supposed to be there - we put it there.

> When I drag and drop the crx file for webstore into Chromium...

Can you clarify what you are trying to do please? This sounds like you are attempting to install the webstore release, but not from the webstore.

**Comment by larry-beck** [comment]
At the time, 3.0.12 was not showing the the webstore, so I downloaded the crx webstore file from github so that when a new release was posted I would auto upgrade to it, but it gave me that error and auto disabled the file and I checked the version on Chrome Webstore and it was still showing 3.0.11, but I see 3.0.12 now there, so I just installed from the online version. Trying to test OTP thus why I tried to manually install 3.0.12 that way.
