### ISSUE TITLE
Improve search to prefer continuous matches

### ISSUE THREAD

**Issue by adtac** [browserpass/browserpass-extension#122]
### General information

-   Operating system + version: Arch Linux
-   Browser + version: Firefox Nightly (2019-04-13)
-   Information about the host app:
    -   How did you install it? `browserpass` from [community]
    -   If installed an official release, put a version (`$ browserpass --version`): 3.0.6
-   Information about the browser extension:
    -   Browserpass extension version as reported by your browser: latest master

---

### Exact steps to reproduce the problem

Consider the following search:

![Untitled](https://user-images.githubusercontent.com/7521600/56329365-1be8d600-6151-11e9-97de-ef520433cb95.png)

### What should happen?

The entire second line should be matched i.e. the email address in the above should be matched, not `amazon.ca` from the first line and my domain from the second line.

### What happened instead?

Parts of the first line and the second line got matched.

**Comment by erayd** [comment]
Can you provide an example of where this is actually a problem? The highlighting shows which parts of the entry the search algorithm used for its match, but a full search like that should still correctly promote the entry you're looking for.

If you would prefer to use substring search only (i.e. not use fuzzy search at all), simply enter a space character prior to your search term - this disables fuzzy search.

**Comment by maximbaz** [comment]
I have completely forgotten to document this!
