### ISSUE TITLE
Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations

### ISSUE THREAD

**Issue by waldgruber** [browserpass/browserpass-extension#128]
### General information

-   Operating system + version: Ubuntu 18.04
-   Browser + version: Firefox 66.0.2 (64-Bit)
-   Information about the host app:
    -   How did you install it? downloaded a pre-built binary
    -   If installed an official release, put a version (`$ browserpass --version`): 
    -   If built from sources, put a commit id (`$ git describe --always`): 3.0.6
-   Information about the browser extension:
    -   How did you install it? webstore,
    -   Browserpass extension version as reported by your browser: 3.0.12
---
### Exact steps to reproduce the problem

1. Go to website login screen, 
2. Enter PGP-password
3. username + password inserted after selection -> login successful
4.no error message is shown
5. Go to another login screen (different website)
6. username + password inserted after selection -> login successful
7. error message is shown "Error: InvalidStateError: A mutation operation was attempted on a database that did not allow mutations"

### What should happen?

no error message shown

### What happened instead?

error message

**Comment by maximbaz** [comment]
Hey, you are a second person telling me about this error. I'll push a bugfix release 3.0.15 now, hope it will help, please tell me if the issue is still present after you update.

**Comment by waldgruber** [comment]
Thank you for the fast fix, it works now without a problem!
Bye-the-way: thank you for a great tool!
