### ISSUE TITLE
Copy username/password always blank

### ISSUE THREAD

**Issue by tlaporte** [browserpass/browserpass-extension#133]
### General information

-   Operating system + version: **Windows 10 Pro**
-   Browser + version: **Firefox 66.0.3**
-   Information about the host app:
    -   How did you install it? 
        **Followed the windows instructions to install the prebuilt release manually**
    -   If installed an official release, put a version (`$ browserpass --version`): **3.0.6**
-   Information about the browser extension:
    -   How did you install it?
        **It was a long time ago, not sure if the old windows script installed it for me or if I got it from the firefox addons page**
    -   Browserpass extension version as reported by your browser: **3.1.0**

### Exact steps to reproduce the problem

1. CTRL + SHIFT + L (or open browserpass by clicking on the icon)

2. Click copy username or copy password

3. Paste the result

### What should happen?
The copied username or password should be pasted.

### What happened instead?
Nothing is pasted.

Autofilling information still seems to work. I think I probably did not try the copy feature with V3 until today.

I have no idea how/where to get logs for this, please let me know if I can provide more information.

**Comment by tlaporte** [comment]
I tried on several different sites, also by opening browserpass and searching for an unrelated site to the page I have open.

**Comment by erayd** [comment]
@larry-beck has experienced something similar on MacOS. His final remark was:

> All seems fine, I tested on another Mac with Firefox release, no issues at all, copy/paste username and password as well as OTP works as expected. I have something restricted in my Firefox release install v66 as I have it heavily privacy locked down, so something turned on/off in Firefox settings is making it not work for copy/paste in my v66, while my v67 beta copy is vanilla, nothing special turned on/off in advanced settings of Firefox. I am closing this now as all issues have been resolved to my knowledge.

@tlaporte Given that you are now also experiencing this issue, it gives us another data point. At present, we have no idea how to reproduce this, and no idea where to even start looking. However, given @larry-beck reported this worked for him in Firefox v67 (beta), are you able to try this and let us know whether it also works for you in that version?

Have you changed any privacy-related settings that might be interfering with it?

**Comment by tlaporte** [comment]
I'll give this a try and post back. I have not changed any privacy settings, but I do run several addons, I will tweak those as well and see if anything in particular resolves it.

**Comment by tlaporte** [comment]
I updated to Firefox 67 beta, and it did not solve the issue.

I also updated tried disabling all my addons and reverting my privacy settings.

**Comment by tlaporte** [comment]
Interesting, on nightly it works. I am going to try backing up my profile and then doing a fresh install of 66.0.3 and see if it works again.

**Comment by tlaporte** [comment]
Works on a fresh install of 66.0.3. I'll start adding all my settings and addons back and see if the issue returns.

**Comment by tlaporte** [comment]
I reinstalled and turned everything I thought I had on back on, and it is still working.

I can't seem to figure out what exactly in my old profile broke things, so I will close this.
