### ISSUE TITLE
autoSubmit not working on basecamp/37signals

### ISSUE THREAD

**Issue by DamienCassou** [browserpass/browserpass-extension#134]
### General information

-   Operating system + version: Fedora 29
-   Browser + version: Firefox 66.0.3
-   Information about the host app:
    -   How did you install it? cloned the git repo and `make`
    -   If installed an official release, put a version (`$ browserpass --version`): 3.0.6
-   Information about the browser extension:
    -   How did you install it? Firefox AMO
    -   Browserpass extension version as reported by your browser: 3.1.0

### Exact steps to reproduce the problem

1. Create a password store entry 37signals.com. Add `autoSubmit: true` to the entry
2. Go to https://launchpad.37signals.com/signin
3. Type <kbd>Ctrl+Shift+f</kbd>
4. The username is correctly filled

### What should happen?

Expected: the password field is now visible

### What happened instead?

Actual: the password field is *not* visible, I have to press "next"

**Comment by maximbaz** [comment]
Feel free to report such cases in #62 🙂 

The reason for what you see is that the markup for their "Next" button does not let us identify it as a submit button, so in Firefox the form is not auto-submitted.

Auto-submit works in Chromium though, which contrary to Firefox supports `debugger` permission and lets us press <kbd>Enter</kbd> for user.

Here's me pressing <kbd>Ctrl+Shift+F</kbd> twice for this domain when having the following pass entry (you can see Yubikey indicator showing up every time after I press the shortcut):

```
password
user: 123456
autoSubmit: true
```

![autosubmit](https://user-images.githubusercontent.com/1177900/56495572-73db6000-64f6-11e9-8900-2f8700032003.gif)

**Comment by DamienCassou** [comment]
Thanks
