### ISSUE TITLE
Chromium 74.0.3729.108 breaks browserpass on Debian

### ISSUE THREAD

**Issue by meskes** [browserpass/browserpass-extension#137]
Debian unstable just updated to chromium 74.0.3729.108 which apparently breaks browserpass. When clicking on the browserpass icon the message "Loading available logins.." appears and stays still it reaches a timeout. No logins are shown, even if there are a couple available. 

I have 3.1.0 installed from the Debian package, but also tried 3.1.0 from the webstore to no avail.

Reverting chromium to 73.0.3683.75 (the prior version in Debian) fixes the issues and browserpass works nicely again. 

Please tell me if there is anything else I can do to debug the issue.

**Comment by maximbaz** [comment]
Hmm, I'm running `Version 74.0.3729.108 (Official Build) Arch Linux (64-bit)` since yesterday and it works quite fine... Can you try Webstore version?

**Comment by meskes** [comment]
Are you using chromium or chrome? The official google chrome  version works for me too.

**Comment by maximbaz** [comment]
Plain Chromium, and it is extra weird that Google Chrome works for you!

**Comment by 532910** [comment]
I confirm this issue!

**Comment by maximbaz** [comment]
Wow! It does sound like a bug on Debian side though, especially if it works in Google Chrome on Debian and in Chromium on Arch.

I wanted to check how Chromium is packaged, this seems to be the place where packaging instructions would be stored, but there's no commit about v74 yet, unless I'm missing something: https://salsa.debian.org/chromium-team/chromium

Do you know if any other extension that uses native messaging works?

I'd suggest you to create a bug against Chromium package for Debian, ask someone knowledgeable to investigate.

**Comment by 532910** [comment]
> Do you know if any other extension that uses native messaging works?

No

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927982

**Comment by maximbaz** [comment]
Hey guys, is this still an issue with the latest Chromium?

**Comment by meskes** [comment]
On Sat, 2019-07-27 at 13:16 -0700, Maxim Baz wrote:
> Hey guys, is this still an issue with the latest Chromium?

I'm running 76.* from Debian Sid and did not notice any problems
lately.

Michael
-- 
Michael Meskes
Michael at Fam-Meskes dot De, Michael at Meskes dot (De|Com|Net|Org)
Meskes at (Debian|Postgresql) dot Org
Jabber: michael at xmpp dot meskes dot org
VfL Borussia! Força Barça! SF 49ers! Use Debian GNU/Linux, PostgreSQL

**Comment by maximbaz** [comment]
Cool, thanks for confirming, closing then 👍

**Comment by 532910** [comment]
> I'm running 76.* from Debian Sid and did not notice any problems lately.

ack
