### ISSUE TITLE
Can't use most dropdowns with browserpass enabled

### ISSUE THREAD

**Issue by lewisdiamond** [browserpass/browserpass-extension#139]
### General information

Linux Archlinux
Chromium 73.0.3683.103
Installed with pacman

Dropdown menus automatically closes right away when clicking to open (i.e. it just flickers but stays closed). If I disable browserpass, then all works fine.

**Comment by maximbaz** [comment]
Could you give me an example link, and describe repro steps? do you activate browserpass at all to see the bug?

**Comment by lewisdiamond** [comment]
Here's an example: https://www.avfgroup.com/support/index.php?lang=en

**Comment by erayd** [comment]
@lewisdiamond Please provide instructions to reproduce this issue with your example. What *exact* steps are you taking?

I have tested that form both before and after triggering browserpass fill, and in both cases all dropdowns (`<select>`) on that page continue to function as expected.

**Comment by lewisdiamond** [comment]
I tried to get consistent repro steps but didn't manage to. The issue may be related to another piece of software so I'll close it here as invalid until I can pin-point the cause.
