### ISSUE TITLE
Feature Request: Allow disabling address username autofill

### ISSUE THREAD

**Issue by adnidor** [browserpass/browserpass-extension#146]
This is related to #117 

Filling in the username with the site name causes issues in a few scenarios:

- The username is pre-filled by the website (e.g. phpldapadmin)
- The username field should not be filled out (e.g. password change forms)
- The pass entry is used in scripts outside of browserpass that can't handle extra data

Of course, in all these scenarios there is the workaround of manually changing/deleting the username, but that's really annoying.

It would be great if there was a checkbox in options "Don't use address as username" for users that encounter these scenarios

**Comment by erayd** [comment]
I don't think the password change example is relevant here. In almost all cases you'll want to be logging in to that same site with a username, and that action is far more common than changing a password.

Are you able to provide some examples of scripts which can't cope with extra data, and for which `head -n 1` is not an option? I'm struggling to think of any. For us to add a global option to disable username fill, it would need to be a significant problem.

I can see how the pre-filled username thing could be an issue. @maximbaz, how would you feel about us adding a `fillLogin: true|false` (default true) option (not global, specified in pass entries only)?

**Comment by erayd** [comment]
@adnidor For the pre-filled username example, is there any reason why you can't simply set the username in the pass entry to match it? Such usernames are generally specified in a config file (or in the markup) for whatever app you're logging into, and don't tend to change.

**Comment by maximbaz** [comment]
> @maximbaz, how would you feel about us adding a fillLogin: true|false (default true) option (not global, specified in pass entries only)? I'm currently thinking no, but a second opinion would be useful.

Also currently thinking no, let's get some real-world examples first 🙂 

> The username is pre-filled by the website (e.g. phpldapadmin)

Just put it in your pass entry

> The username field should not be filled out (e.g. password change forms)

If there's no username field, it will not be filled

> The pass entry is used in scripts outside of browserpass that can't handle extra data

Well `pass` itself doesn't pose any limitations on the contents of the entries, if your external script only needs a password, use `pass entry | head -n1 | myscript`
