### ISSUE TITLE
Error: Error: Attempt to postMessage on disconnected port

### ISSUE THREAD

**Issue by raxod502** [browserpass/browserpass-extension#147]
### General information

-   Operating system + version: Manjaro Linux KDE latest as of 2019-05-06
-   Browser + version: Firefox 66.0.4
-   Information about the host app:
    -   How did you install it? `pacman -S browserpass`
    -   Official release version: 3.0.6
-   Information about the browser extension:
    -   How did you install it? Firefox webstore
    -   Browserpass extension version as reported by your browser: 3.1.1

---

### Exact steps to reproduce the problem

Just open Firefox and click the extension icon.

### What should happen?

I should get a dropdown menu of passwords.

### What happened instead?

I get:

```
Error: Error: Attempt to postMessage on disconnected port
```

**Comment by maximbaz** [comment]
You should follow [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section 🙂

**Comment by raxod502** [comment]
Works like a charm, sorry for the spurious report. I got confused because I was previously using passff, which does install the native messaging hosts for all browsers as part of the host app package.

**Comment by maximbaz** [comment]
There are too many browsers these days... 😄
