### ISSUE TITLE
Suggestion: check autocomplete attributes to fill in username/password

### ISSUE THREAD

**Issue by pimlie** [browserpass/browserpass-extension#148]
While having the console open on a login form I noticed Chrome printed a warning which linked to this page: https://www.chromium.org/developers/design-documents/create-amazing-password-forms

It appears to be recommended for login forms to add autocomplete attribute with values `username` and `current-password` (but not sure if its Chromium only or also Firefox). I noticed this extension doesnt use those yet, maybe it could be added?

**Comment by maximbaz** [comment]
Yeah I think it's a very good idea, thanks!
