### ISSUE TITLE
Error: Unable to fetch and parse login fields: 

### ISSUE THREAD

**Issue by dsanmartins** [browserpass/browserpass-extension#150]
This error when I try to fetch the passwords. At first time it works but then I closed all browser then tried again and I get the error:

`  
{"status":"error","code":24,"version":3000006,"params":{"action":"fetch","error":"Error: exit status 2, Stderr: gpg: imposible pedir contraseña en modo de proceso por lotes\ngpg: descifrado fallido: clave secreta no disponible\n","file":"github.com/xxxx.gpg","message":"Unable to decrypt the password file","storeId":"default","storeName":"pass","storePath":"/home/xxxx/.password-store"}}

`
I also created the file .browserpass.json but nothing happens.

I am using chrome mode incognito, version 71.0.3578.98.
Void Linux x86_64.
gpg version 1.4.23

Thanks!.

**Comment by maximbaz** [comment]
Hey, I think this message means gpg-agent is unable to ask you to enter a master password:

> gpg: imposible pedir contraseña en modo de proceso por lotes

Could you post your `gpg.conf` and `gpg-agent.conf` files? I can show you [mine](https://github.com/maximbaz/dotfiles/tree/master/.gnupg), but I use gpg v2, so I can imagine many defaults have changed...

If you have something custom, try with empty configs?

Maybe upgrade to gpg v2, if that's an option?

**Comment by dsanmartins** [comment]
Thank you! It seems the problem was the version. I have installed both versions and cannot uninstall the older because it breaks other stuffs. Finally I made a symbolic link into /usr/bin (/usr/bin/gpgversion2/gpg -> ../gpg2) and changed the path in browserpass.json.

It solved the issue.

**Comment by maximbaz** [comment]
awesome! enjoy your new extension 😉
