### ISSUE TITLE
Basic Auth Support / HTTP Authentication

### ISSUE THREAD

**Issue by coldcoff** [browserpass/browserpass-extension#153]
Hi!

Thanks for that fantastic tool!

One thing I'm missing, though, this is HTTP Aurthentication (Basic Auth) for some sites.

Of course I have read
https://github.com/browserpass/browserpass-extension#modal-http-authentication
... and for some sites requiring HTTP-Authentication I was able to help myself with the ctrl-g trick that the extension opens the site.

Nevertheless this will for example fail when there are redirects from the site to a "entitlement site (doing the BasicAuth) and back to the site.

I have seen in similar projects that a solution is possible:

https://github.com/passff/passff/issues/27
https://github.com/passff/passff/commit/97c37cf37c5a7a7b4da0c62c7fdd448973c28244

https://github.com/gopasspw/gopassbridge/issues/91
https://github.com/gopasspw/gopassbridge/pull/99
https://github.com/gopasspw/gopassbridge/commit/1b8ea33f7cf83eea0c0d37298fba211da8018db3

Could you please have a look at their solutions and hopefully, probably add HTTP Auth support to `browserpass` as well?

Thanks a lot!

**Comment by erayd** [comment]
The current behavior is deliberate. We don't fill modal authentication if the origin has changed since the user invoked browserpass, in order to guard against leaking credentials to an unknown or unexpected domain.

@maximbaz What do you think? Adding an origin prompt for this might be an option, but it would risk the browser killing us due to blocking the connection while waiting for a response. I'm not comfortable with sending credentials to a different origin without such a prompt due to the risk, but would welcome some other opinions. At the moment, we just forget the credentials when the origin changes.

I personally have one site that has this issue (a university's SSO portal for Office365) - I use dmenu to fill that one, so it doesn't cause any particular problems for my workflow - but not everyone uses (or has easy access to) dmenu.

**Comment by maximbaz** [comment]
I agree that the benefit of not accidentally leaking credentials outweighs the benefits of supporting these kinds of websites in question...

Also, I didn't look much into details, but I heard Chromium is planning to [remove `webRequestBlocking`](https://blog.chromium.org/2019/06/web-request-and-declarative-net-request.html) functionality completely, which might break modal authentication entirely...

**Comment by coldcoff** [comment]
> The current behavior is deliberate. We don't fill modal authentication if the origin has changed since the user invoked browserpass, in order to guard against leaking credentials to an unknown or unexpected domain.
> 
> @maximbaz What do you think? Adding an origin prompt for this might be an option, but it would risk the browser killing us due to blocking the connection while waiting for a response. I'm not comfortable with sending credentials to a different origin without such a prompt due to the risk, but would welcome some other opinions. At the moment, we just forget the credentials when the origin changes.
> 
> ...I use dmenu to fill that one, so it doesn't cause any particular problems for my workflow - but not everyone uses (or has easy access to) dmenu.

@erayd: Could you please share your dmenu trick/workaround? Probably this will also help me for my sites where I'm having that BasicAuth issues?

**Comment by erayd** [comment]
@coldcoff I use this. The script is a complete mess sorry - I wrote it ages ago in a hurry, not intending to distribute it anywhere publicly, and have never actually gone back to clean it up.

```bash
#!/bin/bash

DMENU_FONT='Hack:pixelsize=20'
MODE="$1"
shift

shopt -s nullglob globstar

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )
password_files+=( "clipboard" )

if [ -f "$HOME/.config/pass/history" ]; then
    history_file="$(tail -n 1 "$HOME/.config/pass/history")"
    password_files=( "$history_file" "${password_files[@]}" )
fi

function do_totp()
{
    KEY=$(echo "$1" | base32 -d | hexdump -ve '/1 "%02X"')
    INTERVAL=${2:-30}
    PERIOD=$(( $(date +%s) / $INTERVAL ))
    DIGEST=$(printf "$(printf %016X "$PERIOD" | sed 's/../\\x\0/g')" | openssl dgst -sha1 -mac HMAC -macopt "hexkey:$KEY" | cut -d\  -f2)
    OFFSET=$(( $(printf %d "0x${DIGEST:39}") * 2 ))
    TOKEN=$(( (0x${DIGEST:OFFSET:8} & 0x7FFFFFFF) % 1000000 ))
    printf '%06d\n' "$TOKEN"
}

target=$(printf '%s\n' "${password_files[@]}" | dmenu -i -fn "$DMENU_FONT" $@)
[ -d "$HOME/.config/pass" ] || mkdir -p "$HOME/.config/pass"
[ -z "$target" ] || [ "$target" = "$history_file" ] || echo "$target" >> "$HOME/.config/pass/history"
echo "$target"

[[ -n "$target" ]] || exit 0

if [ "$target" == "clipboard" ]; then
    secret="$(xclip -o -selection clipboard)"
else
    secret="$(pass show "$target")"

    echo "$secret" | head -n 1 | grep -q '^[^\s]\+:.\+'
    if [[ $? -eq 0 ]]; then
        key=()
    else
        key=( 'secret' )
    fi
    key+=( $(echo "$secret" | grep -v '^\s*$' | grep -P '^[^\s]+:\s*[^\s]+' | sed -r 's/^([^:]+):.+$/\1/' | sort | uniq | tr ' ' '\ ') )

    printf '%s\n' "${key[@]}" | grep -q '^login$' && printf '%s\n' "${key[@]}" | grep -q '^secret$'
    if [[ $? -eq 0 ]]; then
        key+=( 'login+secret' )
    fi
    if [[ $(echo "$secret" | wc -l) -gt 1 ]]; then
        key+=( 'everything' )
    fi

    if [[ $(printf '%s\n' "${key[@]}" | wc -l ) -gt 1 ]]; then
        key=$(printf '%s\n' "${key[@]}" | dmenu -i -fn "$DMENU_FONT" $@)
    fi

    if [[ "$key" == "secret" ]]; then
        secret="$(echo "$secret" | head -n 1 | sed -r 's/^[^:]+:\s*//')"
    elif [[ "$key" == "totp" ]]; then
        secret="$(do_totp $(printf '%s\n' "${secret[@]}" | grep "^totp:" | head -n 1 | sed -r 's/^[^:]+:\s*//'))"
    elif [[ "$key" == "login+secret" ]]; then
        login="$(printf '%s\n' "${secret[@]}" | grep "^login:" | head -n 1 | sed -r 's/^[^:]+:\s*//')"
        secret="$(printf '%s\t' "$login")$(echo "$secret" | head -n 1 | sed -r 's/^[^:]+:\s*//')"
    elif [[ "$key" != 'everything' ]]; then
        secret="$(printf '%s\n' "${secret[@]}" | grep "^$key:" | head -n 1 | sed -r 's/^[^:]+:\s*//')"
    fi
fi

if [[ "$MODE" == 'clipboard' ]]; then
    echo -n "$secret" | xclip -selection clipboard
elif [[ "$MODE" == 'type' ]]; then
    echo -n "$secret" | xdotool type -clearmodifiers --file -
fi
```

My workflow for logging into a site with a foreign-origin modal auth prompt is:
1. Browse to whatever page triggers the modal popup;
2. Press <kbd>CTRL + ALT + O</kbd> (global hotkey that runs `~/.password-store/.bin/dmenu.sh type`);
3. Type a few characters to select the correct login;
4. Press <kbd>Enter</kbd> (opens the selected entry and displays options);
5. Type `+` (selects the `login + password` option);
6. Press <kbd>Enter</kbd> (types the login, then <kbd>Tab</kbd>, then the password);
7. Press <kbd>Enter</kbd> (submits the modal).

It's faster than it sounds ;-).

**Comment by maximbaz** [comment]
I'll close this ticket, as it seems we agreed to prefer the currently implemented approach of favoring security over against these special cases. Thanks for the discussion guys 🙂

**Comment by coldcoff** [comment]
@maximbaz, @erayd:
Thanks for your help. That `dmenu` inspiration above is wonderful and also helps me now.

Agree on closing issue.
