### ISSUE TITLE
Google Chrome support?

### ISSUE THREAD

**Issue by ahberg** [browserpass/browserpass-extension#157]
What is the main reason of lack of Google Chrome support? 
I think it will be appreciated if it was clearer in the readme file that this extension don't work with Google Chrome and why.

**Comment by erayd** [comment]
Chrome is fully supported. If you are having an issue with it, please describe what the problem is so that we can help.

**Comment by maximbaz** [comment]
Google Chrome is very well supported, why do you think it's not? 😉

**Comment by ahberg** [comment]
In the readme file you can read "The latest stable version of Chromium or Firefox, or any of their derivatives." maybe will be clearer with "The latest stable version of Chrome/Chromium or Firefox, or any of their derivatives." .

**Comment by maximbaz** [comment]
Google Chrome is a derivative of Chromium, so I think the readme is quite accurate 😉
