### ISSUE TITLE
Browserpass in Google Chrome on Ubuntu

### ISSUE THREAD

**Issue by ahberg** [browserpass/browserpass-extension#158]
In Chromium and Firefox the browserpass extension work for me. But't in google chrome. 

### General information
-   Ubuntu 18.04
-   Google Chrome Version 76.0.3809.100 (Official Build) (64-bit):
-   Information about the host app:
    Installed by Debian package webext-browserpass_3.1.1-2_amd64.deb 
-   Information about the browser extension:
    -   How did you install it?
        Chrome Web Store 
        Version 3.1.1 
---

### Exact steps to reproduce the problem

1. Download and Install the deb package from http://ftp.de.debian.org/debian/pool/main/b/browserpass/webext-browserpass_3.1.1-_amd64.deb

2. Open chrome. Install the extension  from web store.  https://chrome.google.com/webstore/detail/browserpass/naepdomgkenhinolocfifgehidddafch

3. Click on the browserpass icon
### What should happen?
A search box should appear. 

### What happened instead?
 I get this error message "Error: Error: Specified native messaging host not found."

**Comment by erayd** [comment]
This looks like a packaging issue. The message you're seeing means that the configuration file used to point Chrome at the native host app is either missing, or in the wrong place. This may or may not be deliberate - I note that you are installing the package from a Debian repo, and I'm fairly sure that Debian does not actually provide Chrome packages.

@maximbaz Do you know who is responsible for the Debian packages?

@ahberg As a workaround, please see the README for browserpass/browserpass-native - this has instructions for how to manually configure Chrome.

**Comment by maximbaz** [comment]
cc @meskes who is packaging Browserpass for Debian to comment on this.

But in general @erayd is right, we aren't in control of how various distro packages configure browsers, we do however provide a generic way for users to configure any of the supported browser on any of the supported OS, regardless of what specific distro packages do (see [Configuring browsers](https://github.com/browserpass/browserpass-native#configure-browsers) section) 😉 

If you think Debian package could be improved, feel free to talk to @meskes about Debian-specific details of the `browserpass-webext` package, either here on Github or [via email](https://salsa.debian.org/webext-team/browserpass/blob/master/debian/control#L5).

Closing as not actionable for us.

**Comment by ahberg** [comment]
Thanks.
My quick fix for chrome.
sudo mkdir -p /etc/opt/chrome/native-messaging-hosts/
sudo ln -s /etc/chromium/native-messaging-hosts/com.github.browserpass.native.json   /etc/opt/chrome/native-messaging-hosts/com.github.browserpass.native.json

**Comment by mulles** [comment]
I got it working for Chromium Version 83.0.4103.61  on Ubuntu 18.04 like this: 

1. Download webext-browserpass_3.4.1-3_amd64.deb package for your hardware platform from https://packages.debian.org/sid/webext-browserpass 
2. Install with Ubuntu Software
3. Everything should work now. 

It did not work with the package in Ubuntu Repositories: webext-browserpass_2.0.11+dfsg-2_amd64.deb (quite old version) using `sudo apt install webext-browserpass`

Attention if you installed Chromium as Flatpak it does not work. Their is another issue for this:  #93

**Comment by kousu** [comment]
Thanks a lot @mulles! I'm on [GalliumOS 3.1](https://wiki.galliumos.org/News/GalliumOS_3.1) which follows Ubuntu-LTS and so, ultimately, Debian oldstable, and I was getting "Error: Error: Specified native messaging host not found." too. Your tip fixed it up for me.

I doubt many people will run into this, given that Ubuntu 20.10 is already out and 18.04 is almost out of support, but for the few having problems, here's in detail how I got Browserpass working:

1. In Chrome/Chromium, install https://chrome.google.com/webstore/detail/browserpass/naepdomgkenhinolocfifgehidddafch.
2. Remove the old one just for good measure
    ```
    $ sudo apt remove webext-browserpass
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages will be REMOVED:
      webext-browserpass
    0 upgraded, 0 newly installed, 1 to remove and 39 not upgraded.
    After this operation, 2,444 kB disk space will be freed.
    Do you want to continue? [Y/n] 
    (Reading database ... 201536 files and directories currently installed.)
    Removing webext-browserpass (2.0.11+dfsg-2) ...
    ```

3. Get and install the new one
    ```
    $ (cd ~/Downloads/; curl -JLO http://ftp.ca.debian.org/debian/pool/main/b/browserpass/webext-browserpass_3.4.1-4+b1_amd64.deb)
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 1294k  100 1294k    0     0   689k      0  0:00:01  0:00:01 --:--:--  689k
    
    $ sudo dpkg -i ~/Downloads/webext-browserpass_3.4.1-4+b1_amd64.deb 
    (Reading database ... 201569 files and directories currently installed.)
    Preparing to unpack .../webext-browserpass_3.4.1-4+b1_amd64.deb ...
    Unpacking webext-browserpass (3.4.1-4+b1) over (3.4.1-4+b1) ...
    Setting up webext-browserpass (3.4.1-4+b1) ...
    ```
4. Try out the extension in the browser; it immediately worked for me:

    ![Screenshot_2020-11-28_19-06-38](https://user-images.githubusercontent.com/987487/100528660-49ab5300-31ad-11eb-96c9-7e7f8767c1e9.png)


----

I wonder what was wrong with the old package?

Here's the old version:

```
$ dpkg -S webext-browserpass
webext-browserpass: /usr/share/doc/webext-browserpass/changelog.Debian.gz
webext-browserpass: /usr/share/doc/webext-browserpass/copyright
webext-browserpass: /usr/share/doc/webext-browserpass/chromium.d/load_extensions
webext-browserpass: /usr/share/doc/webext-browserpass/README.Debian
webext-browserpass: /usr/share/doc/webext-browserpass/chromium.d
webext-browserpass: /usr/share/doc/webext-browserpass
kousu@ail:~$ apt-cache show webext-browserpass
Package: webext-browserpass
Architecture: amd64
Version: 2.0.11+dfsg-2
Priority: optional
Section: universe/web
Source: browserpass
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Mozilla Extension Maintainers <pkg-mozext-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 2387
Depends: libc6 (>= 2.4)
Recommends: firefox (>= 50) | firefox-esr (>= 50) | chromium
Filename: pool/universe/b/browserpass/webext-browserpass_2.0.11+dfsg-2_amd64.deb
Size: 725596
MD5sum: f410f50195ee658d82286bed25443a8e
SHA1: f1a2fd337aace20770576fbee685355109af83ef
SHA256: 2b8720de6910b4588c00b35d5f1d47d288a6584a82ed7ec1afdf418231782131
Homepage: https://github.com/dannyvankooten/browserpass
Description-en: web extension for the password manager pass
 webext-browserpass is a Firefox/Chromium extension for the password manager
 pass. It retrieves your decrypted passwords for the current domain and allows
 you to auto-fill login forms, as well as copy it to clipboard. If you have
 multiple logins for the current site, the extension shows you a list of
 usernames to choose from.
Description-md5: 9c24e9dd6ded727cba7fcb15ccd7e9d0
```

Here's the new version:

```
$ dpkg -S webext-browserpass
webext-browserpass: /usr/share/doc/webext-browserpass/README.md.gz
webext-browserpass: /usr/share/doc/webext-browserpass/changelog.Debian.gz
webext-browserpass: /usr/share/doc/webext-browserpass/copyright
webext-browserpass: /usr/share/doc/webext-browserpass/changelog.Debian.amd64.gz
webext-browserpass: /usr/share/doc/webext-browserpass/README.chrome
webext-browserpass: /usr/share/doc/webext-browserpass
$ apt show webext-browserpass
Package: webext-browserpass
Version: 3.4.1-4+b1
Built-Using: golang-1.14 (= 1.14.4-1), golang-github-mattn-go-zglob (= 0.0~git20171230.4959821-1), golang-golang-x-sys (= 0.0~git20200523.0598657-1), golang-logrus (= 1.5.0-1)
Status: install ok installed
Priority: optional
Section: web
Source: browserpass (3.4.1-4)
Maintainer: Debian Mozilla Extension Maintainers <pkg-mozext-maintainers@lists.alioth.debian.org>
Installed-Size: 4,420 kB
Depends: fonts-open-sans, libc6 (>= 2.4)
Recommends: firefox (>= 50) | firefox-esr (>= 50) | chromium
Homepage: https://github.com/browserpass
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: web extension for the password manager pass
 webext-browserpass is a Firefox/Chromium extension for the password manager
 pass. It retrieves your decrypted passwords for the current domain and allows
 you to auto-fill login forms, as well as copy it to clipboard. If you have
 multiple logins for the current site, the extension shows you a list of
 usernames to choose from.
```


:shrug:

**Comment by erayd** [comment]
> I wonder what was wrong with the old package?

The old package was the v2 host. It uses an entirely different API than the current v3, and has not been supported by the browser extension for a long time. Hence the error you were seeing.

The v3 API was explicitly designed in a way that allows us to improve Browserpass without breaking anything going forward, so this issue should not crop up again with any future version (although there are other things that can trigger the same error message - most commonly an incorrectly configured host).

**Comment by struckmb** [comment]
The webext-browserpass package seems to install 'com.github.browserpass.native.json' into /etc/chromium/native-messaging-hosts. If I link it manually to ~/.config/google-chrome/NativeMessagingHosts/com.github.browserpass.native.json, the plugin works.
