### ISSUE TITLE
Keyboard shortcuts not working on Mac

### ISSUE THREAD

**Issue by sdan** [browserpass/browserpass-extension#160]
### General information

-   Operating system + version: MacOS + 10.14.6
-   Browser + version: Chrome  76.0.3809.100
-   Information about the host app:
    -   How did you install it?
        Installed via package manager
-   Information about the browser extension:
    -   How did you install it?
        Webstore
    -   Browserpass extension version as reported by your browser: 3.1.1

   
---

### Exact steps to reproduce the problem

1. Keyboard shortcuts don't work

### What should happen?
 They should work
### What happened instead?
Nothing. Passwords are there and I'm able to click them to autofill.

**Comment by maximbaz** [comment]
Try to unset and re-set them manually on `chrome://extensions/shortcuts`, would that help?
