### ISSUE TITLE
Show an explanation for mozilla domains instead of an error.

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-extension#162]
https://github.com/browserpass/browserpass-extension/issues/62#issuecomment-505606225

Browserpass should show an explanation about script injection blocking on mozilla domains instead of "Error: Error: Unable to inject script in the top frame".

**Comment by maximbaz** [comment]
Not sure if this warrants a code change or simply a mention in README (would be nice to avoid browser-specific code as much as possible), but yes, definitely should be more discoverable.
