### ISSUE TITLE
Works in chrome but not in firefox  Error: Error: Attempt to postMessage on disconnected port

### ISSUE THREAD

**Issue by JonLundy** [browserpass/browserpass-extension#167]
### General information

-   Operating system + version: Fedora 29
-   Browser + version: Firefox Quantum 68.0.2
-   Information about the host app:
    -   How did you install it?
         downloaded a pre-built binary
    -   If installed an official release, put a version (`$ browserpass --version`): 3.0.6
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it?
         webstore
    -   Browserpass extension version as reported by your browser: 3.1.1

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section? Yes

---

### Exact steps to reproduce the problem

1. Extension works fine in chrome. 

2. Try in Firefox

3. Click the button get Error: Error: Attempt to postMessage on disconnected port

### What should happen?
 Get password menu
### What happened instead?
Error: Error: Attempt to postMessage on disconnected port

**Comment by maximbaz** [comment]
Hey, please follow again the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) section for Firefox and paste the output here, most probably there was an error and you didn't notice it 😉

**Comment by JonLundy** [comment]
`
> sudo make BIN=browserpass-linux64 configure
/usr/bin/sed -i 's|"path": ".*"|"path": "'"/usr/bin/browserpass-linux64"'"|' browser-files/chromium-host.json
/usr/bin/sed -i 's|"path": ".*"|"path": "'"/usr/bin/browserpass-linux64"'"|' browser-files/firefox-host.json
> sudo make BIN=browserpass-linux64 install
/usr/bin/install -Dm755 -t "/usr/bin/" browserpass-linux64
/usr/bin/install -Dm644 -t "/usr/lib/browserpass/" Makefile
/usr/bin/install -Dm644 -t "/usr/share/licenses/browserpass/" LICENSE
/usr/bin/install -Dm644 -t "/usr/share/doc/browserpass/" README.md
/usr/bin/install -Dm644 browser-files/chromium-host.json   "/usr/lib/browserpass/hosts/chromium/com.github.browserpass.native.json"
/usr/bin/install -Dm644 browser-files/chromium-policy.json "/usr/lib/browserpass/policies/chromium/com.github.browserpass.native.json"
/usr/bin/install -Dm644 browser-files/firefox-host.json    "/usr/lib/browserpass/hosts/firefox/com.github.browserpass.native.json"
> sudo make hosts-firefox
'/usr/lib/mozilla/native-messaging-hosts/com.github.browserpass.native.json' -> '/usr/lib/browserpass/hosts/firefox/com.github.browserpass.native.json'
> sudo make hosts-firefox-user
'/root/.mozilla/native-messaging-hosts/com.github.browserpass.native.json' -> '/usr/lib/browserpass/hosts/firefox/com.github.browserpass.native.json'
`

**Comment by JonLundy** [comment]
i ran the user again without sudo and it works
... though shouldn't the system wide version worked?

**Comment by maximbaz** [comment]
System-wide version is known to have a lesser chance of success, because on different distros Firefox is listening to different paths, whereas user version seems to work for everyone. 

in your case, I bet the Firefox is listening to /usr/lib64 just like here: 

https://github.com/browserpass/browserpass-native/issues/55#issuecomment-483803910

https://github.com/browserpass/browserpass-native/issues/55#issuecomment-483812190

it's still possible to install the system-wide version but you need to override LIB_DIR

in any case, seems everything is great now, enjoy browserpass!
