### ISSUE TITLE
configurable shortcut for Open Browserpass popup

### ISSUE THREAD

**Issue by Loki-Afro** [browserpass/browserpass-extension#169]
Hi there love the extension!

but to avoid conflicts with other extensions or even system wide shortcuts like the ones in i3 - can the shortcut for "Open Browserpass popup" which is currently <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>L</kbd> be made configurable? 

btw <kbd>CTRL</kbd> + <kbd>ENTER</kbd> worked fine for me ;)

**Comment by maximbaz** [comment]
Hey 🙂 

> Can the shortcut for "Open Browserpass popup" which is currently `CTRL + SHIFT + L` be made configurable?

They [are configurable](https://github.com/browserpass/browserpass-extension#first-steps-in-browser-extension) 😉 Although browsers impose some limitations on which shortcuts are allowed, so I'm not sure if `Ctrl+Enter` would be permitted - but give it a try!

> How to change the shortcut:
>
> * Chromium: chrome://extensions/shortcuts
> * Firefox: about:addons > Gear icon > Manage Extension Shortcuts

Let me know if you get any issues with that 😉
