### ISSUE TITLE
Black & white icon

### ISSUE THREAD

**Issue by jakajancar** [browserpass/browserpass-extension#181]
It stands out:

![Screenshot from 2019-10-08 18-01-17](https://user-images.githubusercontent.com/187741/66436810-18deec00-e9f6-11e9-97ef-7067b01fe8b2.png)

**Comment by maximbaz** [comment]
I don't think there's a way to configure extension to use black-white icon in the toolbar alone (if you install any other extension, I assume their icons are also colorful, right?), and we won't be completely replacing our green icon with greyscale one (sorry 😉)

**Comment by jakajancar** [comment]
No idea about other extensions, browserpass is the only one I use with a toolbar icon.

But surely nothing prevents ‘browser_action.default_icon’ to be different than ‘icons’ in the manifest?

**Comment by maximbaz** [comment]
> But surely nothing prevents ‘browser_action.default_icon’ to be different than ‘icons’ in the manifest?

Only one thing: this change will affect every single user, I for one don't want a black & white icon in _my_ toolbar 😉 

I checked Firefox, everything becomes colorful in the toolbar as soon as you install more extensions; correct me if I'm wrong, but I don't think there is any guideline that recommends not to use colors, and I don't think other extensions attempt to do so, therefore I don't consider this is a bug for browserpass as well.

![image](https://user-images.githubusercontent.com/1177900/66459123-a7924e00-ea74-11e9-9f59-fa21ecedc184.png)

**Comment by erayd** [comment]
I agree with @maximbaz. Colorful icons are the norm, and the toolbar icon isn't configurable (it's defined in the manifest).

We will not be changing to a greyscale icon sorry.

**Comment by jakajancar** [comment]
👍🏻 
Makes sense, thanks.
