### ISSUE TITLE
Add support for Home and End keys for popup navigation 

### ISSUE THREAD

**Issue by rEnr3n** [browserpass/browserpass-extension#186]
### General information

-   Operating system + version: Arch Linux
-   Browser + version: Firefox v69.0.3
-   Information about the host app:
    -   How did you install it?
package manager
        
```
$ browserpass --version
Browserpass host app version: 3.0.6
```
-   Information about the browser extension:
    -   How did you install it?
package manager
        
    -   Browserpass extension version as reported by your browser:
```
$ pacman -Qs browserpass-firefox
local/browserpass-firefox 3.4.1-1
```

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

---

### Exact steps to reproduce the problem

1. Open a site where one has multiple accounts.

1. Press `Ctrl+Shift+L`

1. Press `Up` arrow key

### What should happen?
I'm requesting a feature to go back to the end of the list when pressing the up key if the current selected entry is the top one. It should also go to the top of the list when pressing down key if the current selected entry is the bottom one.

### What happened instead?
Nothing. There is no infinite cycle.

**Comment by erayd** [comment]
@rEnr3n The current behavior is by design. We did originally have an infinite cycle, however after some discussion, we decided that having it stop at the top / bottom was better UX. We will not be changing this behavior.

Would implementing the <kbd>home</kbd> and <kbd>end</kbd> keys be a suitable alternative?

**Comment by rEnr3n** [comment]
> Would implementing the home and end keys be a suitable alternative?

That would do.

**Comment by maximbaz** [comment]
Just a note, we also already have `<Tab>` and `<Shift+Tab>` which are just like `<Up>` and `<Down>` but they cycle.
