### ISSUE TITLE
Firefox is deprecating sideloaded extensions

### ISSUE THREAD

**Issue by maximbaz** [browserpass/browserpass-extension#193]
https://blog.mozilla.org/addons/2019/10/31/firefox-to-discontinue-sideloaded-extensions/

Known affected packages:

- `browserpass-firefox` on Arch Linux
- `webext-browserpass` on Debian sid

@meskes do you have any insights into this? Anything we can do? 

I know it's possible to let Mozilla package `.xpi` files and then place it in `/usr/lib/firefox/browser/extensions/${_extension_id}` (in fact this is how most of Firefox extensions are distributed on Arch), but the wording of the announcement implies that this approach is deprecated as well.

**Comment by meskes** [comment]
@maximbaz this is the first time I hear of it, but I agree, it sounds like there will be no way to distribute a working extension in a distro. Sigh!

**Comment by maximbaz** [comment]
Sideloaded extensions are not working since Firefox 80, but luckily placing `.xpi` file in `usr/lib/firefox/browser/extensions/` still works, I implemented this for Arch package.
