### ISSUE TITLE
Symlinks do not show up either in the search or as suggestion

### ISSUE THREAD

**Issue by ismail** [browserpass/browserpass-extension#196]
-   Operating system + version: openSUSE Tumbleweed
-   Browser + version: Chrome 78.0.3904.108 
-   Information about the host app: Browserpass host app version: 3.0.6 from the official repo
-   Information about the browser extension: From the chrome web store
    -   Browserpass extension version as reported by your browser: 3.4.1

I have a few symlinks so that multiple domains use the same login, such as:

```
sisyphus ~ > ls -l .password-store/Internal/build.*
lrwxrwxrwx 1 idoenmez suse 24 Nov 20 21:07 .password-store/Internal/build.opensuse.org -> login.microfocus.com.gpg
```

These do show up in ```pass search```

```
sisyphus ~ > pass search build.opensuse.org
Search Terms: build.opensuse.org
├── Internal
│   └── build.opensuse.org -> login.microfocus.com
````

But if I navigate to build.opensuse.org and click the Browserpass icon I see no passwords are suggested, I search for "build" or "build.opensuse.org" and search comes up empty. This happens for _all_ symlinks.

**Comment by maximbaz** [comment]
Hey, your symlink name must end with `.gpg` extension just like the file name.

**Comment by ismail** [comment]
> Hey, your symlink name must end with `.gpg` extension just like the file name, in other words rename it to `build.opensuse.org.gpg`

Now I feel like an idiot, thanks for your speedy reply!

**Comment by maximbaz** [comment]
No worries 😄 Enjoy the extension!
