### ISSUE TITLE
Support non-prefixed usernames on the second line

### ISSUE THREAD

**Issue by erayd** [browserpass/browserpass-extension#197]
If there is no like containing a username / login etc. prefix, but the file has multiple lines, and the second line has no prefix, assume that the second line is the username.

**Comment by maximbaz** [comment]
This could potentially regress for some people, if they used to have username in file name and free-text notes in the pass file... like so: 

``` 
$ cat john.gpg 
mypassword 
my favorite shopping website 
``` 

Also I remember some tool (pass itself?) creates entries with dashes on the second line, like so 👍 

``` 
$ cat google.com.gpg 
mypassword 
--- 
user: john
``` 

Just some thoughts...

**Comment by erayd** [comment]
Hmm, good point. Are you on the pass mailing list? I was going to do this in order for us to have consistent behavior with what other browser extensions are apparently doing - the subject came up earlier today.

**Comment by erayd** [comment]
Not sure which tool adds a separator line. But I don't think it's pass; I fairly commonly use multiline entries and I've never seen it do this.

What are your thoughts - do you think changing an un-prefixed second line from free text to username is a problematic change, or one that is more useful than any problem it might cause? Or should we just leave it alone unless somebody actually asks for it?

**Comment by maximbaz** [comment]
I'm not on on the mailing list, but have just read the archives :+1: 

I remember now, it was some lastpass->pass migration script, I used it long time ago but I still have some entries that contain this separator :smile: 

I would be fine to add this if we can think of a good way that doesn't break existing workflows, and if we do not add a configuration option for this :slightly_smiling_face: 

I'm less worried about "free-text notes" example (we can just say "add an empty line between password and your notes), but I'm a little worried that users could be using various separators and we will suddenly consider these separators to be usernames...

**Comment by erayd** [comment]
Separators are easy to detect, particularly in situations like this when people aren't likely to be using words as separators. If the number of non-word characters is a significant percentage of the total line length (e.g. over 30% of the line is something other than a letter), then it's a separator. Nothing complicated needed, and JavaScript already includes the regex classes needed to classify the characters.

**Comment by maximbaz** [comment]
In this case let's do it! I'm also planning to finally fix Firefox regressions, so perhaps we can plan for a new release soon :slightly_smiling_face:

**Comment by erayd** [comment]
I think I've changed by mind on this. @maximbaz - are you OK with me closing this as wontfix?

**Comment by maximbaz** [comment]
yep
