### ISSUE TITLE
Your are great!

### ISSUE THREAD

**Issue by DamienCassou** [browserpass/browserpass-extension#201]
You are doing an amazing job with this browser extension. It works perfectly well.

Today I remembered that at some point I asked you to add [muti-step authentication support](https://github.com/browserpass/browserpass-extension/issues/60) to browserpass. This looked complicated to implement. Instead, you implemented <kbd>Ctrl+Shift+f</kbd> which not only solves this problem in a simple way but it also makes it faster to use browserpass in other contexts. That was a great decision!

Thank you so much.

**Comment by maximbaz** [comment]
Thank you :)
