### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-extension#204]
Not sure if it's possible but it will be wery nice to have.
Yes, there is already [Password Store](https://github.com/android-password-store/Android-Password-Store) but it never will can select password to fill automatically even with autofill support

https://github.com/android-password-store/Android-Password-Store/issues/410
![image](https://user-images.githubusercontent.com/988914/66042823-ceed9600-e51d-11e9-893f-78098b7de88a.gif)

Possibly it should use Android-Password-Store as a backend

**Comment by maximbaz** [comment]
It would have been nice indeed, but unfortunately no mobile browser supports communication with any sort of backend... 

We also had some discussions around this here : https://github.com/browserpass/browserpass-native/issues/87

Closing until this becomes possible to implement. 

By the way, autofill in password store works reasonably well for me on android 9, but only for password fields.
