### ISSUE TITLE
unable to make browserpass-extension

### ISSUE THREAD

**Issue by gurucubano** [browserpass/browserpass-extension#205]
### General information

-   Operating system + version: FreeBSD 13 CURRENT r357756
-   Browser + version:FF 73.0
-   Information about the host app:
    -   How did you install it?
        
    -   If installed an official release, put a version (`$ browserpass --version`):
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it?
        
from Github

    git describe --always
0e514e5

-   Browserpass extension version as reported by your browser:

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

---

### Exact steps to reproduce the problem

 cd browserpass-extension
 make
 make -C src
 yarn install
 yarn install v1.12.3
 [1/4] Resolving packages...
 success Already up-to-date.
 Done in 0.54s.
 node_modules/.bin/prettier --write 
 Usage: prettier [options] [file/glob ...]
 
 By default, output is written to stdout.
 Stdin is read if it is piped to Prettier and no files are given.
 
 Output options:
 ....

1.

2.

3.

**Comment by maximbaz** [comment]
On a first glance, sounds like wildcard is not working on FreeBSD? 

https://github.com/browserpass/browserpass-extension/blob/0e514e5bb7fb2159efb2fcaa044242f0f325837f/src/Makefile#L6

It will be difficult for me to reproduce since I never used FreeBSD, would you be interested to investigate this and eventually make a PR? I will help you throughout the way with what I can.

**Comment by gurucubano** [comment]
El día domingo, febrero 16, 2020 a las 10:10:59a. m. -0800, Maxim Baz escribió:

> On a first glance, sounds like wildcard is not working on FreeBSD? 
> 
> https://github.com/browserpass/browserpass-extension/blob/0e514e5bb7fb2159efb2fcaa044242f0f325837f/src/Makefile#L6
> 
> It will be difficult for me to reproduce since I never used FreeBSD, would you be interested to investigate this and eventually make a PR? I will help you throughout the way with what I can. 
> 

I looked into the Makefile (which I should have done before) and it is
just that one must use 'gmake' on FreeBSD. This way it worked. Thanks.

	matthias


-- 
Matthias Apitz, ✉ guru@unixarea.de, http://www.unixarea.de/ +49-176-38902045
Public GnuPG key: http://www.unixarea.de/key.pub

**Comment by maximbaz** [comment]
Cool thanks!

**Comment by gurucubano** [comment]
Using 'gmake' I was able to compile it. But adding it to FF gives the following problem:

going to:  about:debugging#addons and picking up the location of the
extension as: /home/guru/browserpass-extension/firefox/

Mozilla Firefox (73.0)

...

Browserpass

Location
    /home/guru/browserpass-extension/firefox/
Extension ID
    browserpass@maximbaz.com
Internal UUID
    a00256fa-877f-41f0-8893-275cf275b2b5
Manifest URL
    moz-extension://a00256fa-877f-41f0-8893-275cf275b2b5/manifest.json
This WebExtension has a temporary ID. Learn more


click on RELOAD button gives in FF stderr or stdout:

1581925045516   addons.xpi      WARN    Addon with ID browserpass@maximbaz.com already installed, older version will be disabled

click on browserpass icon gives a small pop-up line with
Error: Error: Attempt to postMessage on disconnected port.

Am I still missing something? Btw: The older browserpass icon in the same browser still works pretty fine, i.e. it is not a problem with the passord-store or gpg2.

**Comment by maximbaz** [comment]
Looks like you had this issue in the past? 🙂 

https://github.com/browserpass/browserpass-extension/issues/159
