### ISSUE TITLE
Support the "Request Authentication" dialog

### ISSUE THREAD

**Issue by tillschaefer** [browserpass/browserpass-extension#206]
It would be nice if Browserpass could support the "Request Authentication" dialog, that e.g., pops up when you access a htaccess protected website. 

Currently there is no way to invoke Bowserpass, as the browser controlls are blocked by the dialog. Passff supports this by showing a password selection dialog before the authenthication dialog is presented.

**Comment by erayd** [comment]
Modal authentication is already supported - documentation for that feature is here: https://github.com/browserpass/browserpass-extension/blob/master/README.md#modal-http-authentication

**Comment by erayd** [comment]
Further to the above - the shortcut keys to launch a URL are `CTRL+G` (same tab) or `CTRL+SHIFT+G` (new tab).

**Comment by tillschaefer** [comment]
oh cool, thx for the fast answer
