### ISSUE TITLE
Badly rendered frame and icon in Firefox

### ISSUE THREAD

**Issue by vestingz** [browserpass/browserpass-extension#208]
Probably connected to #190 but also the frame seems broken (see screenshot).

![2020-03-30-19-19-04-screenshot](https://user-images.githubusercontent.com/19933361/77944466-53e41d00-72bf-11ea-8b8b-75c51978d01f.png)

-   Operating system + version: Arch (Linux t440s 5.5.10-zen1-1-zen)
-   Browser + version: Mozilla Firefox 74.0
-   Information about the host app: Browserpass host app version: 3.0.6 (from Arch repos)
-   Information about the browser extension: downloaded latest release from $repo/releases
    -   Browserpass extension version as reported by your browser: 3.4.1

**Comment by maximbaz** [comment]
Hmm I also have a small frame, but it's definitely not that big, and I have it on all other extension popups - how does the frame look for you in uBlock origin extension? I wonder if it's somehow related to a compositor / WM...

![image](https://user-images.githubusercontent.com/1177900/77945870-a9212e00-72c1-11ea-9afc-96d8e57af589.png)


I fear this is outside of our control, if you are able to try to debug the style and see if this is something that can be done, a PR would be much appreciated!

Go here: `about:devtools-toolbox?type=extension&id=browserpass%40maximbaz.com`

Select this in the right corner:

![image](https://user-images.githubusercontent.com/1177900/77946121-22b91c00-72c2-11ea-8af7-9638bf36a72c.png)

Open a popup (it will show error, it's fine).

Select popup.html in the right corner:

![image](https://user-images.githubusercontent.com/1177900/77946315-6449c700-72c2-11ea-94d5-8a8ebd3c468c.png)


On the left side try to hover over `html` tag - on my screenshot below you can see that Firefox highlights the topmost element, and it doesn't highlight the black frame, meaning that frame is outside of our control within styles:

![image](https://user-images.githubusercontent.com/1177900/77946429-8e02ee00-72c2-11ea-8f95-c046e72efa7a.png)

**Comment by vestingz** [comment]
Thank you for your quick reply and your concise help. It is indeed exactly like you suspected: hovering over the html-tag does not highlight that black frame. Changing the system theme doesn't help; actually even the widget preview in LXAppearance does show the same black frame 🤔
The extension displays perfectly well in Chromium, however, even though I enabled GTK designs.
