### ISSUE TITLE
support filling passwords in HTTP Basic Auth dialogs

### ISSUE THREAD

**Issue by pabs3** [browserpass/browserpass-extension#210]
I have some situations where I am connecting to a server that uses HTTP Basic Auth and the browser (Firefox in this case) pops up a dialog to enter the password. It seems that browserpass is currently doesn't support these dialogs, it would be great if it could so that I don't have to resort to the command line and so that I don't have to use copy & paste, which puts the password into the copy/paste history on my desktop.

**Comment by erayd** [comment]
Browserpass already supports this - see the "Modal HTTP Authentication" section of the readme.

Use CTRL+G or CTRL+SHIFT+G to launch a password entry using this method.

**Comment by RalfJung** [comment]
Specifically it seems what I have to do is to open the little panel, enter the domain there, and then press Ctrl-G. I tried half a dozen other things until I figured that out; would be really good to have the docs clarified. :)

Also, the format of the entry (`url: ...`) is documented at the other end of the rather length readme, making it non-trivial to find when just looking for the model HTTP auth informatin.

**Comment by maximbaz** [comment]
For reference, since 3.10.0 this is no longer necessary - shortcuts `Ctrl+G` and `Ctrl+Shift+G` are deprecated, you should open the websites as usual, and browserpass will automatically offer you to choose credentials to send for the modal HTTP auth.

**Comment by maximbaz** [comment]
Please see the tracking issue for this: https://github.com/browserpass/browserpass-extension/issues/370

In particular, this is a current workaround for what you are asking: https://github.com/browserpass/browserpass-extension/issues/370#issuecomment-2770805715

**Comment by RalfJung** [comment]
> For reference, since 3.10.0 this is no longer necessary - shortcuts `Ctrl+G` and `Ctrl+Shift+G` are deprecated, you should open the websites as usual, and browserpass will automatically offer you to choose credentials to send for the modal HTTP auth.

That's awesome, thanks :)
