### ISSUE TITLE
Browserpass sends password to non-active tabs

### ISSUE THREAD

**Issue by lewisdiamond** [browserpass/browserpass-extension#211]
### General information

-   Operating system + version: Archlinux 5.6.13
-   Browser + version: Chromium 83.0.4103.61
-   Information about the host app:
    -   How did you install it?
       Archlinux package
    -   If installed an official release, put a version (`$ browserpass --version`): 3.0.6

-   Information about the browser extension:
    -   How did you install it?
       Package

    -   Browserpass extension version as reported by your browser: 3.4.1

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

---

### Exact steps to reproduce the problem
Steps are unclear, but this issue is security related so it's important to investigate.

1. Press the shortcut keys

2. Browserpass pops up, however, the domain pre-selected is not the current website

3. Backspace and select the correct website

4. Go to the tab of the website that was initially pre-selected, see that the password was entered on that tab instead

### What should happen?
Browserpass should never send password to a tab other than the one currently in focus.

### What happened instead?
The password was sent to another tab.

**Comment by maximbaz** [comment]
Hi, thanks for reporting. Can you consistently reproduce this? I've never seen this happen...

**Comment by erayd** [comment]
Hi - thanks for reporting this. Could you please advise in more detail how you are triggering this behavior? I've not managed to reproduce it here thus far.

**Comment by erayd** [comment]
For reference - [this line](https://github.com/browserpass/browserpass-extension/blob/master/src/background.js#L589) is where the tab selection happens. This code runs every time the popup is opened, and any action from the popup (including hotkeys) should use this tab context until the popup is closed.

**Comment by maximbaz** [comment]
Will close as not actionable, but please feel free to return with steps to reproduce and we will have a look.

**Comment by lewisdiamond** [comment]
I've seen it happen once, it seems like a critical issue but without repro steps, I understand this is difficult. I'll see if I can manage to find a way to reproduce.

**Comment by erayd** [comment]
It shouldn't be possible. We can't reproduce it, so if you can come up with steps to do so, that would be very much appreciated.

If you can't reproduce it, but can point to a flaw in the code that would allow it, that's just as useful. If we can see where it occurs, we can fix it.
