### ISSUE TITLE
login password buttons order

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-extension#214]
![image](https://user-images.githubusercontent.com/14617699/85944884-b4c4d500-b942-11ea-9a09-2ba1b735b1bf.png)

Even though these buttons are well readable I always confuse them, as the common order is login:password.

**Comment by erayd** [comment]
Fair. I have no particular preference.

@maximbaz, do you have an opinion on this one?

Something to consider is that if we change it, we will be conflicting with users' existing muscle memory, which may potentially result in them pasting a password somewhere a username ought to be (and thus having their password end up in logs). This risk is likely small, but not nil.

**Comment by 532910** [comment]
> pasting a password somewhere a username ought to be

it always be visible in this case

> having their password end up in logs

it's possible only after sending the form, just filling it is not enough

**Comment by erayd** [comment]
> it's possible only after sending the form, just filling it is not enough

That is incorrect; some sites proactively send the username field before submission (especially in signup forms, which often do so to check availability). That said, my point here was muscle memory, which will often result in the form being submitted before the user realises something is wrong, even if the mistake is visible.

**Comment by maximbaz** [comment]
I think this is not the first time this request comes up, I would be okay swapping the buttons. 

I think muscle memory risk is not nil but acceptable, given us making the UI more intuitive.

**Comment by erayd** [comment]
OK. Let's swap them.

**Comment by maximbaz** [comment]
Was fixed by #229, will be part of the next release 👍
