### ISSUE TITLE
generate new password 

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-extension#215]
What about to add support for a new password generation?

**Comment by erayd** [comment]
@maximbaz is looking after that feature. It's a significant piece of work though; I'm not sure how far along he's gotten with that.

**Comment by 532910** [comment]
So it's a dup, sorry.

**Comment by maximbaz** [comment]
Yep, still a wanted feature and our most upvoted request ever, but time doesn't permit to properly finish it, am hoping community would be willing to help 🙂  Posted details here: https://github.com/browserpass/browserpass-extension/issues/61#issuecomment-650750349
