### ISSUE TITLE
synchronization

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-extension#216]
Please add `pass git push | pull` buttons.
While this is not strongly required right now, it will be nice to have them with support for a new password generation #61

**Comment by erayd** [comment]
We won't be doing this one sorry. Too much scope-creep; we don't want to become a whole UI for git, and would need to deal with things like multiple repos (which ones should be pulled / pushed, where should per-repo buttons go?), merge conflicts, etc.

We will add a git commit when an entry is edited / created, and will document how to use a post-commit hook to do pushes etc.
