### ISSUE TITLE
update password

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-extension#217]
Similar to a new password generation #61 it'd be nice to have an ability to update current passwords.

There is [pass-update](https://github.com/roddhjav/pass-update) helper, but I'm not sure it's suitable for this issue.

**Comment by maximbaz** [comment]
Agreed - #61 also covers edit and delete functionality, and I do envision a password generation functionality, so I think this will be covered by #61 🙂 

![image](https://user-images.githubusercontent.com/1177900/85950702-a84e7580-b95e-11ea-929f-324f18931b79.png)

Lets get this form done first and then see if it needs to be improved, e.g. by keeping the previous password somewhere visible
