### ISSUE TITLE
[Firefox] pinentry program not being triggered

### ISSUE THREAD

**Issue by craigcabrey** [browserpass/browserpass-extension#218]
### General information

-   Operating system + version: Arch Linux (5.7.5-zen1-1-zen)
-   Browser + version: 77.0.1
-   Information about the host app:

```
$ browserpass --version
Browserpass host app version: 3.0.6
$ pacman -Qs browserpass
local/browserpass 3.0.6-5
    Native host app for Browserpass, browser extension for zx2c4's pass (password manager)
local/browserpass-chromium 3.5.0-1
    Chromium extension for Browserpass, browser extension for zx2c4's pass (password manager)
local/browserpass-firefox 3.5.0-1
    Firefox extension for Browserpass, browser extension for zx2c4's pass (password manager)
```
    -   Browserpass extension version as reported by your browser: 3.5.0
---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

---

### Exact steps to reproduce the problem

1. Navigate to site with a login page

2. Select the relevant entry from the browserpass

3. Nothing happens

### What should happen?

I'm expecting the pinentry program to be invoked. When I preauthenticate (e.g. I manually run `pass -c some/path` and authenticate via pinentry and return to the browser), using browserpass works as expected. It seems only seems to be when gpg-agent needs to be authenticated that there is an issue.

```
$ cat .gnupg/gpg-agent.conf 
pinentry-program /usr/bin/pinentry-gnome3
```

I tested the extension on Chrome and it works as expected.

### What happened instead?

gpg-agent remains unauthenticated due to no prompt being triggered.

**Comment by mradke** [comment]
The same issue is happening under NixOS v.20.03 with the global option `programs.browserpass.enable = true;`

**Comment by maximbaz** [comment]
Correct, nothing in browserpass ever triggers pinentry, we are only executing gpg and relying on it to ask your pin if necessary. Please try other pinentry apps and have a look at #155 for some other insights 🙂
