### ISSUE TITLE
Error: Unable to enumerate password filesError: An unexpected error occurred

### ISSUE THREAD

**Issue by xpire** [browserpass/browserpass-extension#219]
### General information

-   Operating system + version: Windows 10 Pro 2004 with WSL 1 running Ubuntu 18.04.4 LTS
-   Browser + version: Firefox 78.0.2 (but I've installed in Chrome and Brave with no issue like this)
-   Information about the host app:
    -   How did you install it?
        installed backend from precompiled binary (linux64-3.0.6)
    -   If installed an official release, put a version: Browserpass host app version: 3.0.6
-   Information about the browser extension:
    -   How did you install it?
        installed extension from firefox addon
    -   Browserpass extension version as reported by your browser: 3.5.0

### Exact steps to reproduce the problem

N.B. I'm actually unsure why it has happened, but I still want to have an Issue on it in case others have run into the same issue, or to ascertain that its only happening to me. 

1. install gopass
```
gopass 1.8.4 (a5442953608c3380efdddcfe2f6d6d123fd5605f) go1.11.4 linux amd64
```
2. install browserpass, backend 3.0.6, and firefox frontend. (follow all steps in wiki, use wsl-pinentry)

3. About 30% of the time, when clicking on the extension, the error in the title appears. This does not seem to happen for chromium based browsers, as I have both chrome and brave open at the same time with the same backend but they open fine without any issues. 

I'm just wondering if anyone has seen this bug before on firefox.

### What should happen?
It should not fail with this error
### What happened instead?
It sometimes fails with this error (just tested by repeatedly opening the extension, 9/30 times it fails with this error, for seemingly no reason)

This is an image of the issue, (I have materialfox installed on my firefox, so that is why it looks chromium)
![image](https://user-images.githubusercontent.com/30570611/87237110-5d8c2d80-c435-11ea-8427-74553acd6b3a.png)

**Comment by maximbaz** [comment]
Hi, have a look at that thread: https://github.com/browserpass/browserpass-extension/issues/111

**Comment by maximbaz** [comment]
Closing as not our bug
