### ISSUE TITLE
Option to cache data briefly

### ISSUE THREAD

**Issue by C4K3** [browserpass/browserpass-extension#234]
Hi. I use browserpass with the pgp key stored on a yubikey configured to require touch on use.

This works great, but there is one annoyance: Sites that ask for the username and password on separate pages (examples: [accounts.google.com](https://accounts.google.com/) &bull; [explore.garmin.com](https://explore.garmin.com/Account/LogOn?stage=2)) To autofill the username, I have to Ctrl-F, touch the yubikey, click submit, and then I have to Ctrl-F and touch the yubikey again to fill the password.

(I'm sure it's annoying for others just having to Ctrl-F twice, without adding the yubikey touch into the mix.)

It would be convenient if there were an option to cache and autofill data for some brief (configurable?) period, so that after autofilling the username and clicking submit and being taken to the next password-entry page, browserpass can autofill the password without the user having to do Ctrl-F again.

Thank you.

**Comment by maximbaz** [comment]
Hi! We have considered this in the past, but ended up choosing not to implement it in the end, please see here the full discussion: https://github.com/browserpass/browserpass-extension/issues/60

That's actually one of the reasons we have implemented Ctrl+Shift+F in the first place 🙂 

Yes it's not ideal but there are some downsides in trying to implement a solution that tries to be too smart...

**Comment by C4K3** [comment]
Thanks, I didn't find that issue when searching.
