### ISSUE TITLE
all passwords are listed on about: pages

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-extension#235]
Not sure if this a bug, but all passwords are listed on about: pages, like preferences for example.

![image](https://user-images.githubusercontent.com/14617699/93448695-8c62cc00-f8dc-11ea-8c5d-e020de58d6ab.png)

**Comment by maximbaz** [comment]
Yeah it is by design, we pre-filter the popup with the domain in the current tab, but if there is no domain, then we show popup without a filter, which could be useful on a new tab in particular, say if you want to open a new link via browserpass that requires basic auth.

**Comment by 532910** [comment]
1. I'm agree to show it on a blank page, but disagree to show on about:preferences
2. Fill password button should be disable on no-domain pages.

**Comment by erayd** [comment]
@532910 

1. Can you clarify why please?
2. No. There are legitiate reasons to be filling on non-domain origins (e.g. into extension preferences screens), so we need to ensure this functionality remains available.

**Comment by 532910** [comment]
OK (:
