### ISSUE TITLE
password characters colors

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-extension#237]
Digits and special characters are shown in yellow. Not sure this is a good, as they might be mistaken as a delimiters.

**Comment by erayd** [comment]
Can you clarify please? In what way do they look like delimiters?

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/93454101-2af22b80-f8e3-11ea-9e62-26c787adfba3.png)

Are `-` just a delimiters like in a card number, or a part of password?

**Comment by erayd** [comment]
They are part of your password. The **Secret** field in that screen does not alter your passwords at all; it displays them verbatim, exactly as they are stored in the pass file.

Can you please clarify why this is confusing? What would lead you to believe that we are modifying your password?

**Comment by 532910** [comment]
> They are part of your password. The Secret field in that screen does not alter your passwords at all; it displays them verbatim, exactly as they are stored in the pass file.

I know (:

> Can you please clarify why this is confusing?

Different colors. It's just my perception

> What would lead you to believe that we are modifying your password?

I don't think the password is modified, but formatted, like phone number, that is shown as 123-45-67 (while 123456 just stored).

**Comment by erayd** [comment]
Thanks for clarifying.

I don't think that this behavior should be changed. No use will have *all* their passwords contain no numbers and no special characters other than dashes, so the small minority of users that might wonder about this will learn pretty fast, and the utility of being able to easily tell the difference between letters, and other character types, is too high to warrant getting rid of this feature.

If we find that more than a couple of users ask about it (although this seems unlikely), then we can simply document the behavior.

**Comment by 532910** [comment]
maybe highlighting in three different classes be better:
letters: color1
number: color2
special characters: color3

**Comment by erayd** [comment]
Easy enough for us to do, but how would that help?

**Comment by 532910** [comment]
1. there will be no gray characters without meaning
2. pass generate distinguishes symbol characters (`--no-symbols, -n`), so I believe they should use a separate color.

**Comment by erayd** [comment]
1. There are *already* no characters without meaning. We display the password verbatim; every character in that field is part of your password.

2. How does having two different colours for symbols and digits help? What problem does it solve? _"Because `pass generate` does it"_ isn't enough of a reason; we aren't trying to be a clone of `pass`.

**Comment by 532910** [comment]
Right now only non letters are emphasized, this confuses. It's good for zero and capital O, but why hyphen is so special to be yellow?
Coloring all characters will make all of them emphasized.

Using the third color for symbols will help to distinguishes passwords with and without symbols. Visually. Not all websites allow symbols in passwords.

**Comment by erayd** [comment]
Can you please clarify what, *precisely*, is confusing about having symbols the same colour as numbers? What actual problem does this cause that is both likely to be encountered by users, and significant enough to warrant changing the browserpass interface?

If a site doesn't allow passwords with symbols, then the user won't be saving such a password for that site. Why is _"this password contains one or more symbols"_ something we even need to care about pointing out to the user?
