### ISSUE TITLE
Firefox add-on decryption functionallity suddenly slow, 'Open Details' option not working, asks for passphrase for every action

### ISSUE THREAD

**Issue by Th3Tr00p3r** [browserpass/browserpass-extension#246]
### General information

-   Operating system + version:
windows 10.0.19041

-   Browser + version:
Firefox 81.0.2 (64-bit)

-   Information about the host app:
    -   How did you install it?
    Installed through Linux terminal, using package manager.

-   Information about the browser extension:
    -   How did you install it?
    Extension installed as Firefox add-on.
    -   Browserpass extension version as reported by your browser:
    3.7.1

### Issue

Hi,
Yesterday, I installed the firefox browser add-on, placed gpg binary path (`C:\Program Files (x86)\GnuPG\bin\gpg.exe`) in place as well as the password-store path.
Everything was working great and as fast as I would expect the decryption to take from using `gpg --decrypt` in terminal.
Today, after restarting my laptop (I'm not sure if that's what changed things) I tried using the add-on and it now acts funny - takes a long time (5-15 sec) to load the pinentry-qt GUI and a long time to autofill after filling the correct passphrase. Also, the useful 'Open Details' option doesn't show after the passphrase checks out.
Additionally, I don't remember having to fill in the passphrase after every single action, which I now do.

I would appreciate you help.

Regards,
Ido

**Comment by maximbaz** [comment]
Hello,

Both launching `pinentry` and deciding when pinentry should ask for passphrase is something outside of browserpass' control, it's entirely based on your own configuration, which unfortunately means I won't be able to investigate on my own. But I can try to give you some help to hopefully find the root cause 🙂 

When you install on Windows using Linux terminal, does this mean it is installed in WSL? If so, make sure to check [this section](https://github.com/browserpass/browserpass-native#install-on-windows-through-wsl) of the docs, but sadly I must report that based on other users' feedback WSL has several bugs and is the most unstable way of running browserpass...

I'm not even sure why pinentry would be asking pin every time, maybe it's because `gpg-agent` is being killed for you? Or you have configured some very short TTL value in `gpg-agent.conf`?

It sounds like you have browserpass native host on Linux subsystem, but `gpg` on Windows, is this right? Maybe try to move to using `gpg` in Linux subsystem as well?

If you have any ideas you would like to run by me, please feel free to ask. Hope you'll find what's causing the issue...

**Comment by Th3Tr00p3r** [comment]
> It sounds like you have browserpass native host on Linux subsystem, but gpg on Windows, is this right?
That's correct.

> Maybe try to move to using gpg in Linux subsystem as well?
I tried that in the beginning (before it even worked for me) but I get an error saying the "`gpg`" file does not exist (perhaps since it is expecting an `.exe`). In any case, it used to work fine so I was trying to find out what happened.

I believe I fixed it jut now?!.. I tried to see if I'm able to "quickly" decrypt a password-store password (which sits in the linux subsystem folder) using the windows-based gpg from windows command prompt and it worked. Right afterwards, Browserpass was able to freely access all of the passwords.
I then killed `gpg-agent` and tried to do it all from Browserpass - also worked, quickly as before.
Any ideas why that would fix it?...

I guess I have my workaround for if this happens again, though I'm not completely sure this is what fixed it.

**Comment by anh193** [comment]
> It sounds like you have browserpass native host on Linux subsystem, but `gpg` on Windows, is this right? Maybe try to move to using `gpg` in Linux subsystem as well?
I have both the host and `gpg` on Linux subsystem here, followed the entire instructions for installing on WSL but ended up having `Error: Error: Native host has exited.` when clicking in the extension on Chrome. Could you be of help? Appreciate it!

- Anh

**Comment by maximbaz** [comment]
> Any ideas why that would fix it?...

Thanks for the update, glad to see that you "solved" it, although I also have no clue why it fixes this....

> `Error: Native host has exited`. when clicking in the extension on Chrome. Could you be of help? Appreciate it!

Do you also have `gpg` installed on Windows? It looks like [pinentry-wsl.ps1](https://github.com/diablodale/pinentry-wsl-ps1) is relying on GnuPG for Windows...

**Comment by anh193** [comment]
> Do you also have `gpg` installed on Windows? It looks like [pinentry-wsl.ps1](https://github.com/diablodale/pinentry-wsl-ps1) is relying on GnuPG for Windows...

No I have `gpg` key on  the Linux subsystem. Havent done the `pinentry-wsl-ps1` setup though, but in the FAQ, it says to do it if `If you can see passwords, but unable to fill forms or copy credentials, you likely have issues with your gpg setup.`, I thought I'm not that far yet?

**Comment by maximbaz** [comment]
Good point, yes that is correct - in that case I would probably recommend just carefully tracing back the steps, so a browser talks to native host binary specified in json file, a json file points to a wrapper script containing path to browserpass binary, just double check that you didn't accidentally make a typo somewhere... 

while doing that you could also try to post here exactly what you did and the contents of all the files, maybe I'll be able to spot a typo 👍

**Comment by anh193** [comment]
> while doing that you could also try to post here exactly what you did and the contents of all the files, maybe I'll be able to spot a typo 👍

Thanks for your reply! What I did is as follows:
1. Installed `Browserpass native host` package on Ubuntu subsystem by `sudo apt install webext-browserpass`, the installation went through without errors.
2.  Run Windows installer downloaded from the `Github release page`. It installed new files in `C:\Program Files\Browserpass`.
3.  Created a new file named `browserpass-wsl.bat` inside the folder above, with the following content 
`@echo off`
`bash -c "/usr/bin/browserpass-linux64 2>/dev/null"`
4. Modify `path` in `chromium-host.json` to be `"path": "C:\\Program Files\\Browserpass\\browserpass-wsl.bat",`
5. Install the Chrome extension from Chrome web store.
Done.

**Comment by maximbaz** [comment]
Hmm I can't spot any obvious errors, let's try next to confirm that your bat file is able to call browserpass, try to replace the contents of bat file with 

    bash -c "/usr/bin/browserpass-linux64 --version"

and then just run that bat file from powershell - do you get the version printed?

**Comment by anh193** [comment]
> and then just run that bat file from powershell - do you get the version printed?

Bingo!!!
`/usr/bin/browserpass-linux64: No such file or directory` 
I suppose I need to run this `make browserpass-linux64` ?

**Comment by maximbaz** [comment]
apt install webext-browserpass should have installed that binary... maybe try to uninstall and install it again?  or maybe they just install it in a different location now? 

if all fails yes you can try to compile the binary yourself and put it in that path, or even just grab the binary from github releases...

**Comment by anh193** [comment]
> if all fails yes you can try to compile the binary yourself and put it in that path, or even just grab the binary from github releases...

That's right :) I got the binary from github release and now the extension can display the password entries but cant copy them though, I think now it's now to set up the `pinentry-wsl-ps1` ;) Thanks a lot!

**Comment by maximbaz** [comment]
Will close since it seems both of you managed to get a working browserpass, enjoy 🙂

**Comment by anh193** [comment]
Superb work, thanks @maximbaz  and everyone involved!
