### ISSUE TITLE
username differs slightly for same password depending on site - any idea or best practice?

### ISSUE THREAD

**Issue by coldcoff** [browserpass/browserpass-extension#247]
I have an account which is used via ActiveDirectory on several internal sites. I want to share *one* encrypted password file and not duplicate it.

Issue is that on some internal sites I need to login with `username: full-email` and the `password` and on other sites I need to login with only the first part of the email (without the `@domain`) and the `password`.

Using the same symlinked file in`pass`/`browserpass` will either always fill full-email or first part of the email without the `@domain`). So some are wrong.

But creating and maintaining two files (with different usernames) means updating the password twice on every change.

Any idea how to handle such a situation best?

**Comment by maximbaz** [comment]
I had the exact same experience at some point and I ended up using two files, I don't think we can do any better than this, even thought it's a single identity behind the scenes, from the perspective of any two given websites they simply want a specific username and a specific password, it's just so happens that the passwords are the same on different websites...

**Comment by coldcoff** [comment]
Hmm. ok :-(
Thank you for your quick response!

(I suggest leaving the issue open/visible for some more time, maybe some other user jumps in with an idea that we did not see yet.)

**Comment by maximbaz** [comment]
Looks like it has been discussed sufficiently (thanks for sharing your approach, looks very reasonable!), thus closing.
