### ISSUE TITLE
doesn't work on chromium/arch

### ISSUE THREAD

**Issue by chovy** [browserpass/browserpass-extension#250]
`Error: Error: Specified native messaging host not found.`

I have pass-host running

**Comment by maximbaz** [comment]
https://github.com/browserpass/browserpass-native#installation

**Comment by maximbaz** [comment]
No followup, closing

**Comment by cindrmon** [comment]
I also have this issue recently. Is there any explanation to why it causes this error for chrome-based browsers? I'm using brave right now, and I also have the same issue. I installed `browserpass`, `browserpass-chromium` and the chrome extension from the chrome web store. Is there a missing step I took for it? Thank you.

**Comment by maximbaz** [comment]
`browserpass-chromium` is only for chromium, to configure Brave you need to follow steps here: 

https://github.com/browserpass/browserpass-native#configure-browsers

**Comment by cindrmon** [comment]
i see, thanks.
