### ISSUE TITLE
OTP does not work since main integration

### ISSUE THREAD

**Issue by be-neth** [browserpass/browserpass-extension#251]
### General information

-   Operating system + version:

I use browserpass from Archlinux repository on Archlinux.

-   Browser + version:

Firefox archlinux version 84.0.1-1.

-   Information about the host app:
    -   How did you install it?

Via archilnux package manager.

 -   If installed an official release, put a version (`$ browserpass --version`):

« Browserpass host app version: 3.0.7 » 

-   Information about the browser extension:
    -   How did you install it?

Via Archlinux package manager.

   -   Browserpass extension version as reported by your browser:

Firefox report browserpass extension version 3.7.1.
(community/browserpass-firefox 3.7.1-2 (firefox-addons) [installed])

---

In the past, I use the browserpass OTP extension for generating my OTP and it work fine.
After the integration into the main browserpass addon, I never succeed to have an OTP generated by the extension. I use `pass otp` from command line as a workaround to generate code but it becomes a little bit annoying.

I have enabled option in addon preference to allow OTP generation. But I never see any difference at all.
How can I debug that ?

Thanks for your help,

**Comment by maximbaz** [comment]
Hey, could you please post an example password entry that you use (with redacted info of course) and a screenshot of the extension when you press `>` button on it? 

If I remember correctly, after you fill username/password, OTP token will automatically be copied to clipboard (just like it was in the separate extension), but you can also reopen browserpass popup, go to `>` for details and you should see the token there.

**Comment by be-neth** [comment]
Pass store example for github.com :

~~~
mygithubpassword
url: *.github.com/login
login: be-neth
otpauth://totp/GitHub:be-neth?secret=SECRET&issuer=GitHub
~~~

> screenshot of the extension when you press > button on it?

Interesting, I never use this button before, and it seems to not work on my environment. It trigger as usual the GPG pinentry program to give the PIN code for my Nitrokey (I use a gpg key, nitrokey pro 2) but after returning from pinentry program, nothing is shown on firefox and nothing is copied to my clipboard.

I use Wayland environment with sway and wlroots as wayland compositor.

**Comment by be-neth** [comment]
Ok I feel stupid now…

> If I remember correctly, after you fill username/password, OTP token will automatically be copied to clipboard

You are right, I never check that OTP code was automatically generated and copied to my clipboard. It works like that, it is fine for me.
We can close this issue, thanks for your time.

Ps: Maybe we can add to the FAQ that OTP are copied automatically to clipboard when option is enabled ? But I think you do not want to promote OTP usage.

**Comment by erayd** [comment]
> It trigger as usual the GPG pinentry program to give the PIN code for my Nitrokey (I use a gpg key, nitrokey pro 2) but after returning from pinentry program, nothing is shown on firefox...

This is because Firefox closes the popup window as soon as it loses focus, even if it's just losing focus to your pinentry program. Unfortunately, there is nothing we can do about that - there is no API in Firefox that allows us to hold the popup open. If you have gpg-agent keep a live session, that will work around the issue and allow you to re-open the pass entry without pinentry getting in the way (although it's probably a good idea not to have too long a session timeout before re-prompting).

**Comment by maximbaz** [comment]
I agree we should mention somewhere that OTP token is being placed in the clipboard 👍

**Comment by erayd** [comment]
Agreed. Something of an oversight I think; I should have done that when I implemented it.
