### ISSUE TITLE
Pass OTP copying OTPauth URL instead of a generated code

### ISSUE THREAD

**Issue by webcoderkz** [browserpass/browserpass-extension#256]
### General information

-  MacOS 11.2.1 (BigSur)
-   Chrome 88:
-   Information about the host app:
    -   Browserpass host app version: 3.0.7
-   Information about the browser extension:
    -   Browserpass extension version as reported by your browser: 3.7.2

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?
- Not related

---

### Exact steps to reproduce the problem

1. Go to a website protected with 2fa (binance.com)
2. Press CMD+SHIFT+L, choose credentials for this website, login and password filled successfully
3. Now we see, 2FA window with a single input, whenever i try CMD+SHIFT+L and choose OTP credentials, it says: "Error: Error: No fillable forms available for fields: login, secret"

![image](https://user-images.githubusercontent.com/5739191/108317605-bbad9a00-71e8-11eb-88e2-4b688ef66e9e.png)

### What should happen?

It should paste generated 2FA code

### What happened instead?

An error: "Error: No fillable forms available for fields: login, secret""

I can see generated OTP code only when i go in to details by pressing Ctrl+O and manually selecting OTP and copy.

**UPDATE**

On a vultr.com, it pastes "Login" value instead of a "Secret", so the only way is to go in to details (CTRL+O) and manually copy a secret key from here?

![image](https://user-images.githubusercontent.com/5739191/108318308-ce749e80-71e9-11eb-9173-3c1bb7a07c66.png)

**Comment by erayd** [comment]
This is not a bug. Autofill is intended to enter your username and password. When you try to autofill on the OTP page, you are receiving that error message because Browserpass cannot find anywhere on that page that a username or password should go.

To enter the OTP code, simply paste it (CMD+V) - it's already been automatically copied to the clipboard during step 2 of your original post. You do not need to select it again.

**Comment by webcoderkz** [comment]
@erayd but token is not getting copied after my step 2, login and password successfully inserted, but my clipboard contains no 2fa generated code. What i'm doing wrong?

**Comment by erayd** [comment]
Aah, I see - the problem is that you have the OTP seed in a separate file. If you put it in the same file as the password, then it will work correctly.

**Comment by webcoderkz** [comment]
How can i merge them? my "email@gmail.com" has just 1 string with a password itself and otp contains otpauth url.

**Comment by erayd** [comment]
Just put the otpauth URL as an additional line in the same file as your password.

**Comment by webcoderkz** [comment]
Also when i insert a new otp auth:

`zbarimg -q --raw qrcode.png | pass otp insert website.com/email@gmail.com`

I can just use the path to an existing entry?

**Comment by erayd** [comment]
You should use `append` instead of `insert`.

The documentation for `pass otp` can be found [here](https://github.com/tadfisher/pass-otp).
