### ISSUE TITLE
Export / import / access browserpass settings

### ISSUE THREAD

**Issue by flyinggreenfrog** [browserpass/browserpass-extension#257]
How can I export / import / access browserpass settings?

E.g. for Firefox settings in about:addons for browserpass, I use several custom store locations.

Under `~/.mozilla/firefox/<PROFILE>` I couldn't find anything related to browserpass (e.g. inside `prefs.js`).

My goal is to configure browserpass settings with Ansible in an automated way.

Maybe you could give me a hint how I can achieve that.

**Comment by maximbaz** [comment]
Hello, some of the options can be placed in `.browserpass.json` file in the root of the password store (see [here](https://github.com/browserpass/browserpass-extension#options)), but custom store themselves have to be configured in the browser settings - we store the settings in local storage by the way, if you can find how to import / export local storage, it could be another option.

**Comment by flyinggreenfrog** [comment]
Ok, I will see if I can find out more, how to import / export local storage. Thanks for now.

**Comment by maximbaz** [comment]
No problem! 🙂
