### ISSUE TITLE
Impossible to uninstall from firefox

### ISSUE THREAD

**Issue by callegar** [browserpass/browserpass-extension#262]
### General information

Linux, ubuntu 20.04 (in fact kubuntu)
Firefox 87.0
Installed via firefox add on finder
Browserpass 3.4.1

### Exact steps to reproduce the problem

1. go to the firefox add on manager

2. click the ... to the side of brow

3. notice that the option to uninstall is grayed out

### What should happen?

It should be possible to uninistall the extension

### What happened instead?

It is impossible to uninstall the extension from firefox even in safe mode.

**Comment by maximbaz** [comment]
Hi, try to uninstall browserpass package, if it's greyed out it's probably because addon was in fact installed by the Ubuntu package and not via store.

**Comment by maximbaz** [comment]
Will close, assuming the question got answered.
