### ISSUE TITLE
Feature Request: Fill additional fields

### ISSUE THREAD

**Issue by njdart** [browserpass/browserpass-extension#263]
Some login forms, such as AWS' IAM login page, require additional fields to be filled to log in. It would be convenient if browserpass could be instructed of additional fields and values to use when filling out login forms.

In the below screenshot, the AWS IAM login page also expects an account ID to be filled. This can be provided by the URL, but for example logging out and back in to another account returns you to an almost valid login form but with a possibly incorrect account id.

![2021-04-20-23:28:01-screenshot](https://user-images.githubusercontent.com/1180858/115471866-982abe00-a230-11eb-8b38-83c249fcecf9.png)

My thinking is that a pass entry such as the following could be read by browserpass and the additional fields prefixed with `input:<key>:` would be used as values for the inputs matching `<key>`. 
```
my-super-secure-password
---
url: https://123456789012.signin.aws.amazon.com/console
username: njdart
input:account: 123456789012
```

How users discover what an appropriate key is without using developer tools need more thought.

Also, what does `<key>` matches against? input's `name` property seemed sensible, but may not cover other cases where a form is not used. id/class similarly may not be sufficient on their own. A `querySelector()` string seems like a lowest-common-denominator but would likely present parsing/escaping issues.

Thoughts welcome

**Comment by maximbaz** [comment]
Hello, definitely a good thought, we actually have a thread for that already: #74 🙂
