### ISSUE TITLE
FR: Be able to remove saved filled password from the list if it doesn't match the domain

### ISSUE THREAD

**Issue by fourstepper** [browserpass/browserpass-extension#269]
Hi,

For a few things, I have one shared password (sheesh), that is typically not linked to a domain.

When I fill it out, it is automatically added and presented upon future visit - NEAT! But sometimes, I misstype, missclick, fill something else out that is not the thing I intended to fill out (usually ctrl+shift+f + enter). It would be great to be able to remove this from the recommendations going into the future.

What do you think?

**Comment by maximbaz** [comment]
Great suggestion (not so great password policy, if I may nudge you 😝 ), it will be implemented by https://github.com/browserpass/browserpass-extension/pull/260

**Comment by fourstepper** [comment]
Oh, that's great. Sorry for missing that one.

Yeah, it's continuous work :) for those edge cases though, you know :wink: 

All the best and thank you!
