### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by thoastbrot** [browserpass/browserpass-extension#274]
### General information

-   Operating system + version: **OSX, Big Sur, x86**
-   Browser + version: **Chrome 92.0.4515.131**
-   Information about the host app:
    -   How did you install it? **brew**
    -   If installed an official release, put a version (`$ browserpass --version`):
    **$ browserpass-darwin64 --version
    Browserpass host app version: 3.0.7**
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it? **chrome webstore**
    -   Browserpass extension version as reported by your browser: **3.7.2**

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

No, I get a listing of my entries. No, I think I let the brew package handle the configuration.

---

### Exact steps to reproduce the problem

1.  Opened the extension popup, chose an entry, clicked on it

### What should happen?

Fill in form (user, pass)

### What happened instead?

popup went oopsie, message: 
`Error: Unable to fetch and parse login fields: Error: {"status":"error","code":24,"version":3000007,"params":{"action":"fetch","error":"Error: exit status 2, Stderr: gpg: Entschlüsselung mit Public-Key-Verfahren fehlgeschlagen: Inappropriate ioctl for device\ngpg: Entschlüsselung fehlgeschlagen: Inappropriate ioctl for device\n","file":"somesecret.gpg","message":"Unable to decrypt the password file","storeId":"default","storeName":"pass","storePath":"/Users/myusername/.password-store"}}`

I can decrypt the named file with gpg in a terminal, and as soon as I did that, the extension behaves as it should. I assume the gpg password UI is missing/failing.

**Comment by maximbaz** [comment]
Hi there! Weird! Are you able to decrypt that file by hand, using `gpg --decrypt`? I would definitely recommend looking into `gpg` setup, could it be for example that your `gpg` is very old?

**Comment by maximbaz** [comment]
Sorry I somehow totally overlooked your last paragraph. If manually unlocking gpg helps, it's a case of pinentry not being opened up. It's nothing browserpass can do, you have to investigate what's wrong with your configuration. 

Start from this place: https://github.com/browserpass/browserpass-extension#error-unable-to-fetch-and-parse-login-fields

Search also issues, there were quite a lot of similar cases 🙂 And feel free to post here if you get stuck, I don't have a Mac to try but maybe I'll be able to give you some advice nonetheless. 

Good luck, hope you'll find it 😉

**Comment by thoastbrot** [comment]
Thank you, I already checked issues for "inappropriate ioctl" and it seems I'm the first one running into this. 

I'll try a "script-in-the-middle" attack.

**Comment by maximbaz** [comment]
Cool, do make sure to try with `pinentry-mac` too if you haven't already - it's usually the root cause of problem you describe, despite the difference in error message 🙂 

Will close as it's not really actionable for browserpass, but as I said feel free to post here if you are in doubt and we'll try to help.

**Comment by thoastbrot** [comment]
For anyone stumbling across the same issue: I installed gnupg via brew, but was missing the graphical part contained in gpg-suite.

**Comment by maximbaz** [comment]
Awesome that you found the cause! Consider making a PR to the homebrew formula, if this is a required dependency. And enjoy the app 🙂

**Comment by thoastbrot** [comment]
uninstalled gnupg-suite, installed pinentry-mac as suggested - it's the better solution (no conflicts, no nested package installer).

**Comment by subdavis** [comment]
For anyone still struggling:

* `brew install gpg-suite` was the fix for me.
* `pinentry-mac` didn't do anything for me.
