### ISSUE TITLE
Use the url field for matching the website

### ISSUE THREAD

**Issue by mbrunnen** [browserpass/browserpass-extension#286]
I do not understand, why the information in the `url` field is not used.
It would greatly enhance the usability, it would just work out of the box,
without the need of selecting the correct password item for each browser.
I guess it would be necessary to decrypt all passwords at startup for caching the data.

**Comment by maximbaz** [comment]
The issue you pointed out, having to decrypt the entire password store, is exactly the reason it's not supported. 

However there are ways to avoid selecting the correct password item by hand for every website, as this would eliminate the protection against phishing attacks, please see "organizing password store" section in README for the strategies.
