### ISSUE TITLE
Feature request: Fedora Support

### ISSUE THREAD

**Issue by KemonoElite** [browserpass/browserpass-extension#291]
### General information

-   Operating system + version: Fedora

## Feature request: Fedora Support

Fedora has basically become the new Ubuntu of Old, I do think there would be many people that would be intrested in using this if it was available to them.

I don't think I've seen any support for it as of writing this. I have looked in many places and haven't seen anything thus far. If there is some sort of support already in place it would probably be nice to have it documented.

Thank you for your time!

**Comment by maximbaz** [comment]
Hello, you can definitely use it on Fedora today, there is really nothing special to document, just follow the installation instructions and you'll get it running. And if something is confusing or goes wrong, don't hesitate to ask! 😉 

We do have a few distro packages that automate some of the installation steps, but that's just for convenience, and fully community-driven. If you or anyone else end up creating one, just make a PR to make it more discoverable 😉 

As said, if you have any questions don't hesitate to ask, I'll close the ticket as it's generally supported and up to the Fedora community to package this extension if anyone is up for the challenge 🙂
