### ISSUE TITLE
Options are not displayed in Google Chrome

### ISSUE THREAD

**Issue by azuenko** [browserpass/browserpass-extension#295]
### General information

-   Operating system + version: MacOS Monterey 12.4
-   Browser + version: Google Chrome Version 102.0.5005.115 (Official Build) (x86_64)
-   Information about the browser extension:
    -   How did you install it? Via Chrome Web Store
        
    -   Browserpass extension version as reported by your browser: 3.7.2

---

### Exact steps to reproduce the problem

1. Download Google Chrome 102.0.5005.115

2. Install Extension v3.7.2

3. Open Extension options at chrome://extensions/?options=naepdomgkenhinolocfifgehidddafch

### What should happen?

Options should be displayed properly

### What happened instead?

Options are not displayed:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/7202664/173824795-ca88474e-97df-48f2-9741-874ee4697e23.png">

### Workaround

1. Download the extension as a .zip archive, unpack it
2. In `manifest.json` change `options_ui.open_in_tab` from `false` to `true`
3. On Chrome Extensions chrome://extensions/ page enable Developer Mode
4. Manually install the extension through 'Load Unpacked'

### Notes

* Works fine on Chromium 99.0.4844.51
* After updating Chromium to 102.0.5005.115, failed to work properly: some elements are displayed but not the save button:

<img width="679" alt="image" src="https://user-images.githubusercontent.com/7202664/173828097-baabfaab-2385-4820-a3ee-b76f732018a0.png">

**Comment by maximbaz** [comment]
Hi, thanks for reporting, we are tracking this in #293 👍
