### ISSUE TITLE
Browserpass can't find gpg binary

### ISSUE THREAD

**Issue by GiulioDeveloper** [browserpass/browserpass-extension#296]
### General information

-   Operating system + version: MacOS Monterey
-   Browser + version: Brave 102.1.39.122
-   Information about the host app:
    -   Installed from brew tap amar1729/formulae
-   Information about the browser extension:
    -   Installed via chrome store

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?
Yes
---

### Exact steps to reproduce the problem

1. Click on browser extension icon

2. Try to fill desired password (I do get the list of my password from pass)

### What should happen?
Fill in my password

### What happened instead?

3. Getting error:  Error: Unable to fetch and parse login fields: Error: {"status":"error","code":22,"version":3000008,"params":{"action":"fetch","error":"Unable to detect the location of the gpg binary to use","message":"Unable to detect the location of the gpg binary"}}

I have tried everything I managed to find about the issue:
- Installed pinentry-mac from brew
- Changed .conf files in /.gnupg/ (I didn't have those files so I created them, don't know if it was allowed) to work with pinentry
- Created a symlink to the gpg bin in usr/local/bin/gpg
- Restarted several times gpg and browser

Nothing seems to work.
Thanks in advance

**Comment by maximbaz** [comment]
Hi there, you can specify the full path to gpg binary in extension options, could you please try it that helps?

**Comment by GiulioDeveloper** [comment]
The extension option panel in Brave doesn't save what I input: i write my path (the one from brew which is where I have gpg) and close the panel; when I reopen it I can't find the changes. I also don't know where to find the option json

**Comment by maximbaz** [comment]
Ah yes you are being affected by #293 

There is also a possibility to configure that path by creating a json file with the setting in password store dir, could you perhaps try that instead? 

https://github.com/browserpass/browserpass-extension#options

**Comment by GiulioDeveloper** [comment]
Thanks I solved it!!!
