### ISSUE TITLE
Support Firefox for android interfacing with Password Store app

### ISSUE THREAD

**Issue by pravi** [browserpass/browserpass-extension#300]
### General information
This is a feature request to add support for Android. Currently only BitWarden extension is available. It would be nice to have support in Firefox for Android. Password Store app can already handle pass git repo but some bank sites don't allow copy pasting so need a browser plugin to work and I have to use my laptop or type in the long complex password which is error prone.

-   Operating system + version: Android 11
-   Browser + version: Firefox 91
-   Information about the host app:
    -   How did you install it?
        Its a feature request to support Android.
    -   If installed an official release, put a version (`$ browserpass --version`):
    -   If built from sources, put a commit id (`$ git describe --always`):
-   Information about the browser extension:
    -   How did you install it?
        
    -   Browserpass extension version as reported by your browser:

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

---

### Exact steps to reproduce the problem

1. Go to add ons menu

2. Look for browserpass

3.

### What happened instead?
Only Bitwarden is available.

**Comment by erayd** [comment]
What you are asking for is not technically possible, sorry. Browserpass is an extension that requires a native component interface; not something that Android's sandboxing model would allow. Mozilla also doesn't allow the general use of extensions on Android yet, only a handful that they have whitelisted.

If you wish to use a Pass repository on Android, your best bet is probably [this](https://play.google.com/store/apps/details?id=dev.msfjarvis.aps). It has reasonably good autofill support.

**Comment by pravi** [comment]
Thanks. This looks promising, though it did not work for fednetbank.com I will report an issue there.
