### ISSUE TITLE
Outdated PGP Signing Key

### ISSUE THREAD

**Issue by tomix1024** [browserpass/browserpass-extension#301]
Apparently @maximbaz has changed his PGP key at some point.
See for example here:
https://archlinux.org/todo/rebuild-packages-signed-by-eb4f9e5a60d32232bb52150c12c87a28feac6b20/

In the [browserpass-native repository](https://github.com/browserpass/browserpass-native/commit/68580ddae23e258155f70925726f61f3f3ad23a9), the correct PGP key (consistent with [maximbaz.com](https://maximbaz.com/pgp_keys.asc) and [keybase.io](https://keybase.io/maximbaz) ) is updated in the `README.md` and the releases are signed with that key.

In this repository, the old RSA signing key seems still to be used.

### Exact steps to reproduce the problem

1. Import the signing key key.
```
$ curl https://maximbaz.com/pgp_keys.asc | gpg --import
pub   ed25519 2021-10-24 [SC]
      56C3E775E72B0C8B1C0C1BD0B5DB77409B11B601
uid           Maxim Baz <git@maximbaz.com>
uid           Maxim Baz <maximbaz@archlinux.org>
uid           Maxim Baz <pgp@maximbaz.com>
sub   ed25519 2021-10-24 [S]
sub   ed25519 2021-10-24 [A]
sub   cv25519 2021-10-24 [E]
pub   ed25519 2021-10-24 [SC]
      56C3E775E72B0C8B1C0C1BD0B5DB77409B11B601
uid           Maxim Baz <git@maximbaz.com>
uid           Maxim Baz <maximbaz@archlinux.org>
uid           Maxim Baz <pgp@maximbaz.com>
sub   ed25519 2021-10-24 [S]
sub   ed25519 2021-10-24 [A]
sub   cv25519 2021-10-24 [E]
```

2. Download release files
```
$ wget https://github.com/browserpass/browserpass-extension/releases/download/3.7.2/browserpass-webstore-3.7.2.crx
$ wget https://github.com/browserpass/browserpass-extension/releases/download/3.7.2/browserpass-webstore-3.7.2.crx.asc
```

3. Check the signature of a release file.
```
$ gpg --verify browserpass-webstore-3.7.2.crx.asc
gpg: assuming signed data in 'browserpass-webstore-3.7.2.crx'
gpg: Signature made Di 19 Jan 2021 00:49:10 CET
gpg:                using RSA key 8053EB88879A68CB4873D32B011FDC52DA839335
gpg: Can't check signature: No public key
```

### What should happen?
The signature should be ok.

### What happened instead?
The public key that was used for signing was not found.

**Comment by maximbaz** [comment]
Hello, sorry for the late response. You are completely right that I changed the key since the last release, the old key however is not compromised. You can still get it via `$ gpg --recv-keys EB4F9E5A60D32232BB52150C12C87A28FEAC6B20` (using `--keyserver keys.openpgp.org` for example), and you can also get it via `$ curl https://maximbaz.com/pgp_keys_rsa4096.asc | gpg --import`. I will of course make sure to sign any future releases with the new key, and will keep this issue as a reminder!

**Comment by maximbaz** [comment]
`3.8.0` is signed with my latest key, thanks again for being vigilant :+1:
