### ISSUE TITLE
Weird layout

### ISSUE THREAD

**Issue by ayykamp** [browserpass/browserpass-extension#327]
### General information

-   Windows 10:
-   Chromium Version 117.0.5938.63:
-   Information about the host app:
    -   How did you install it? Ubuntu under WSL
    -   If installed an official release, put a version (`$ browserpass --version`): Browserpass host app version: 3.1.0
-   Information about the browser extension:
    -   Chrome Web Store
    -  3.7.2

---

### Exact steps to reproduce the problem

1. Open Extension pop up

2. Have any passwords with a long path

### What should happen?
See passwords normally

### What happened instead?
![image](https://github.com/browserpass/browserpass-extension/assets/32194363/831704ab-2876-40ca-bdbe-ff2cdd990094)
![image](https://github.com/browserpass/browserpass-extension/assets/32194363/6a5f4a9c-06df-444c-9d19-3c3bb15a1a56)

**Comment by erayd** [comment]
> I haven't any activity on this project in a while. If the author is still around and doesn't have time to address this, please let me know and I'll try to get a PR submitted tonight. If the project is abandoned, then I'm happy to take over if no one else wants to.

It's not abandoned, but I'm extremely short on time (and I think @maximbaz might be also?). If you'd be willing to fix this issue, it would be greatly appreciated - thank you!

**Comment by maximbaz** [comment]
PR would certainly be appreciated, thanks!

**Comment by erayd** [comment]
Thanks @mcexit - much appreciated. #328 is merged.
