### ISSUE TITLE
Call for testers! Add/Edit/Delete functionality in 3.8.0

### ISSUE THREAD

**Issue by maximbaz** [browserpass/browserpass-extension#331]
Hello everyone,

We are preparing to ship `3.8.0`, which includes new functionality to add, edit and delete pass entries.

Your help with testing this new functionality is extremely appreciated!

Here's how:

1. Grab the latest RC release for your browser (currently [3.8.0-rc1](https://github.com/browserpass/browserpass-extension/releases/tag/3.8.0-rc1), or [build yourself](https://github.com/browserpass/browserpass-extension#building-the-extension) from the `master` branch.
  a. Required version of native host is [3.1.0](https://github.com/browserpass/browserpass-native/releases/tag/3.1.0), but you likely have it already, since it was released in March 2023.
3. Follow the [Installation](https://github.com/browserpass/browserpass-extension#installation) instructions to load it into your browser.
4. Use it! :rocket:  **Please make sure to try out the new add/edit/delete functionality** :sparkles:
5. Leave a comment after testing for a bit, so that we can gauge how many people have tried it out.

Thank you all very much for your help, and for your patience waiting for this important feature to be released!

And don't forget to praise @patgmiller for his astonishing contributions to implement this new feature for us all!

**Comment by cyrinux** [comment]
Hi,

Thanks for the features, I try it on chromium and Firefox, nothing to say against this great additions, all good for me! 👍

**Comment by patgmiller** [comment]
I tested Chrome in Ubuntu and Darwin, it worked fine for me. I think one improvement to consider would be to adjust the auto close behavior after save / delete. If you have multiple edits having to reopen every time is a minor annoyance. But its not a big deal, so unless more people feel the same it could also just remain as is.

**Comment by maximbaz** [comment]
`3.8.0` is out, thank you guys :heart:
