### ISSUE TITLE
Undocumented shortcut for opening a website

### ISSUE THREAD

**Issue by rapidcow** [browserpass/browserpass-extension#332]
Hi, this isn't any specific bug so I'll just jump to my question. I was reading the [Modal HTTP authentication][] section of `README.md` and was confused about what it meant by opening a website with Browserpass:

[Modal HTTP authentication]: https://github.com/browserpass/browserpass-extension/tree/d03fbf895aa83d97bce1e0a523b6292303f317f4#modal-http-authentication

> If you want Browserpass to handle modal authentication, you must **open these websites using Browserpass**.

After a bit of digging, I found that pressing <kbd>Ctrl</kbd>+<kbd>G</kbd> was how you open one from `popup/interface.js` [L310-314][code]:

```javascript
function keyHandler(e) {
    /* start of my quoted code */
    switch (e.code) {
        case "KeyG":
            if (e.ctrlKey) {
                this.doAction(e.shiftKey ? "launchInNewTab" : "launch");
            }
            break;
    }
    /* end of my quoted code */
}
```

[code]: https://github.com/browserpass/browserpass-extension/blob/d03fbf895aa83d97bce1e0a523b6292303f317f4/src/popup/interface.js#L310C1-L314C19

Was this obvious or is this something that needs clarification in the README?

**Comment by maximbaz** [comment]
Hello! The key shortcuts are documented in this section: 

https://github.com/browserpass/browserpass-extension#available-keyboard-shortcuts

But a PR with a suggestion on how to make it clearer is definitely welcome - perhaps a link to that section? What do you think?

**Comment by rapidcow** [comment]
Dang I apologize for the oversight, I think I would have seen that if I read linearly or just did a simple search :c

That said I do think it helps to pack relevant information in that section for those who want to get an idea of what the url field is for. I made a PR for just that change: #333

**Comment by rapidcow** [comment]
Thank you for your promptly replies too! I am impressed to see how well-maintained this project is :)
