### ISSUE TITLE
Extension prompting for "Update native host app"

### ISSUE THREAD

**Issue by comatory** [browserpass/browserpass-extension#337]
### General information

-   Operating system + version: macOS Monterey 12.6.6
-   Browser + version: Firefox 114.0.1
-   Information about the host app:
    -   How did you install it?
        Installed via brew, via [this user-contributed cask](https://github.com/amar1729/homebrew-formulae) which is the "official way" of installing, the installation reports version `3.1.0`. I had to use command `brew upgrade --build-from-source browserpass` to bump the version due to [this issue](https://github.com/Amar1729/homebrew-formulae/issues/28)
    -   If installed an official release, put a version (`$ browserpass --version`): 3.1.0
    -   If built from sources, put a commit id (`$ git describe --always`): I would assume it's the latest one on `master` branch `fd13db29719103577159ca9d724dc5c8d060de6b` but not sure how I could check it
-   Information about the browser extension:
    -   How did you install it?
        Firefox add-on gallery
    -   Browserpass extension version as reported by your browser: 3.8.0

---

> If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

I'm not getting errors when opening the popup.

---

### Exact steps to reproduce the problem

1. Open the popup

2. See the message "Update native host app"

3. Make sure `browserpass-native` is up-to-date

4. Re-open the popup

### What should happen?

The message should not be present

### What happened instead?

The message is present

**Comment by maximbaz** [comment]
Hello! This could either mean that you got an older version of the native host installed (an issue in the homebrew formula), or that you have two browserpass installations in different locations, and the browser is configured to pick up the old one.

The homebrew formula suggests to use this command to configure the browser: `make hosts-firefox-user`.
So let's assume that's how you did it.

Here's what would get executed:
https://github.com/browserpass/browserpass-native/blob/ed246ee62824a49a16e50482889f11f4e18b6934/Makefile#L466-L469

Open that json file, you'll see a full path to the browserpass binary. Is that the location of the browserpass binary that you'd expect? What version does that binary report?

You can manually edit the path in that json file, pointing to a correct binary (you can even grab one from the [latest release](https://github.com/browserpass/browserpass-native/releases/tag/3.1.0)), and see if the issue disappears.

If you confirm the issue with packaging, I would recommend to share your findings with the author of the formula, to hopefully prevent others from experiencing the same issue.

**Comment by comatory** [comment]
Hi 👋 
Thanks for the detailed instructions, it helped me to debug it. I'm not sure what I did wrong before but for some reason I was still on `3.0.8`. Maybe something happened meanwhile but when I ran upgrade for `browserpass` today, it correctly bumped the version. Then I just ran the make script and now it's working. Thank you for your help!

**Comment by maximbaz** [comment]
Awesome, enjoy the extension! 😊
