### ISSUE TITLE
Can you change the structure of search? 

### ISSUE THREAD

**Issue by seriiserii825** [browserpass/browserpass-extension#339]
Hi. 
Now application how work. 
Yout type in input file-name.gpg and after press enter
login = filename
password = first line of the file. 

May be it's better in search to find filename
login = first line of the file
password = second line. 

Because sometimes i can add the name of the project. 
For ex.
I have one project with login admin, and also another project with the same login. 

And i need to add filename like admin-project1 and admin-project2
After press enter, need to clear -project1 from login input. 

Thanks for great extension.

**Comment by maximbaz** [comment]
Hello! Happy to say that what you ask is already supported today :wink: 

Have a look here, specifically points 2 and 3: https://github.com/browserpass/browserpass-extension#organizing-password-store

Let me know if you have further questions!
