### ISSUE TITLE
Page load speed drop

### ISSUE THREAD

**Issue by nikicat** [browserpass/browserpass-extension#342]
Hello, I've recently decided to switch to the Pass from KeepassXC and chosen Browserpass as a browser integration addon. Unfortunately, I've noticed a significant performance drop when loading sites (YouTube for example) after I've imported all my passwords to the pass database (~6.4K entries).
When I disable Browserpass the page load time comes back to normal.
When I run the Firefox profiler it shows that CPU time is spent inside the Browserpass extension.

![image](https://github.com/browserpass/browserpass-extension/assets/329262/18fa3af7-e12c-432d-ad3a-8a6bbc7b87ac)

### General information

-   Archlinux
-   Firefox 122
-   Information about the host app:
    -   How did you install it? AUR
    -   Browserpass host app version: 3.1.0
-   Information about the browser extension:
    -   How did you install it? AUR
    -   Browserpass extension version as reported by your browser: 3.8.0

### Exact steps to reproduce the problem

1. Open YouTube with browserpass enabled and a pretty big password database.
2. Observe a slower page loading speed.

### What should happen?

In my opinion, Browserpass should not analyze the page until a user interacts with the extension. If this contradicts Browserpass' design at least I suppose that page load speed should not depend on the database size.

### What happened instead?
I've observed a slower page load speed.

**Comment by maximbaz** [comment]
Thanks for sharing all the details! 

My immediate impression is that it will likely be solved by this forgotten PR https://github.com/browserpass/browserpass-extension/pull/230 - @erayd shall we have a fresh look at that?

**Comment by nikicat** [comment]
@maximbaz Thank you for your rapid answer! I can confirm - when I installed the extension from #230 and enabled the "Hide badge counter" checkbox the performance drop disappeared. When I disable the checkbox the performance drop is back again.

**Comment by BastienDurel** [comment]
since a few days/weeks, I noticied the plugin-in often get stuck on loading login list :

![image](https://github.com/browserpass/browserpass-extension/assets/682171/e67f2f13-c30e-423f-b486-96e15115e562)

I have to close/reopen the menu, often more than once, to get my list :/ Can this be related ?
