### ISSUE TITLE
extension not finding passwords and leaving processes with "[browserpass-lin] <defunct>"

### ISSUE THREAD

**Issue by pniederlag** [browserpass/browserpass-extension#348]
# browserpass zombies

After a recent update I noticed a very laggy behaviour of the browserpass-extension. When looking into the details I found that <defunct> procecsses pile up in my processlist

` [browserpass-lin] <defunct>`

This happens quite frequently while sometimes the list of passwords just works as intented. No pattern that makes the difference betwenn "creates zombie" and "works as intented" found yet. When a password is found no zombie process shows up. Once a password is found future lookups tend to work until the browser is restarted.

# Used Versions

```
chromium --version
Chromium 123.0.6312.122 for TUXEDO Computers GmbH
```

```
browserpass-linux64 --version
Browserpass host app version: 3.1.0
```

```
lsb_release -a
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

any tips on further debugging?

**Comment by maximbaz** [comment]
Thanks for the report! I'm wondering if this could be explained (and solved) by https://github.com/browserpass/browserpass-extension/issues/342, have you seen that thread by any chance?

**Comment by pniederlag** [comment]
Thx for your feedback, actually yes, I was thinking about it but forgot to link it.

I tested a local build on master with merged branch "hide-badge" (which #342 refers to), zombie-processes don't show up anymore.

So my problem is currently solved, thx. Probably would make sense to ship an update 3.8.1 ?

**Comment by maximbaz** [comment]
Thanks for confirming! Yeah we should get that merged...

**Comment by pniederlag** [comment]
unfortunatly <defunct> processes still show up after a long working day

**Comment by maximbaz** [comment]
I'm not sure! If you manage to discover any way to reproduce this, please share... I have a little doubt that a browser extension can somehow control processes that browser starts :thinking:

**Comment by maximbaz** [comment]
Does it ever happen that you cancel an operation? You open popup but close it before list is rendered, or you ask browserpass to fill out a form but don't complete the operation (e.g. by not touching yubikey to confirm, if you are using one)?

**Comment by pniederlag** [comment]
Hi @maximbaz  the problem really sticks around without me having a clue... could be memory or timinig issues  ;(
