### ISSUE TITLE
bad color visibility

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-extension#64]
It's hard to see lightgray on darkgrey, grey on yellow:
![image](https://user-images.githubusercontent.com/14617699/55426421-697c1500-558d-11e9-823d-ef7f8338b3eb.png)

**Comment by maximbaz** [comment]
You refer to the top bar with "github.com" and "Search logins" right? Especially the latter is super invisible on your screenshot, I agree

**Comment by 532910** [comment]
I mean:
1. repository name (&)
2. path (IT/bugtrackers/)
3. name github.com
4. "Search logins..."
5. site name: gihtub.com (grey on yellow)

**Comment by maximbaz** [comment]
Basically the entire design 😅

**Comment by 532910** [comment]
Key and login icons are visible, and significant more contrast than all other elements

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/55673939-37352500-58b7-11e9-9f8f-138f2ac0544f.png)

`Search logins...` is still hard visible.

**Comment by 532910** [comment]
Other colors looks good.

**Comment by 532910** [comment]
![image](https://user-images.githubusercontent.com/14617699/55674065-26d17a00-58b8-11e9-93dc-c8ab8a309516.png)

store name is also hard visible
green background in the previous version was nicer

**Comment by maximbaz** [comment]
Awesome!

Badge background color will be configurable later on, we anyway need to support this to distinguish multiple stores 😉 

Thanks for the screenshot, I was wondering why your "Search logins..." is so much dimmer comparing to what I see on my side, turns out Firefox adds some default opacity! Will push a fix in a moment.

**Comment by 532910** [comment]
Moreover, colors are strange!

For example: Simple Tab Groups (https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/)
used "default" colors: absolutely same as ff uses itself on the panel:

bg: 323234, fg: bebebe

browserpass-extension uses own colors:
bg: 393939, fg: c4c4c4

**Comment by maximbaz** [comment]
Well I deliberately want to have control of how popup looks, not rely on "default" styles, precisely to avoid situations like when one browser adds strange "opacity" rules making placeholder completely unreadable. And these colors are what I chose and I stand by them 🙂

**Comment by 532910** [comment]
> Badge background color will be configurable later on, we anyway need to support this to distinguish multiple stores wink

GREAT!

**Comment by 532910** [comment]
Icon itself is also bad visible. Specially when button is clicked. But changing hue a bit makes is significant more contrast:

![image](https://user-images.githubusercontent.com/14617699/55674716-0eb22880-58c1-11e9-8468-38b86d5cd1c3.png)

I don't insist on this color, but it should be more contrast.

**Comment by maximbaz** [comment]
I met @Tobaloidee today, a logo designer, they promised to help us with the icon 😉 

https://github.com/browserpass/browserpass-extension/pull/65#issuecomment-480523005

We could definitely play with colors, I want it to look good on both dark-gray, light-gray and white backgrounds. Maybe even some red / violet color? 🤔 Let's wait for their proposal first.

**Comment by 532910** [comment]
Really, with the last version 3.0.4 I was able to understand that new icon is not just a P with some garbage, but P with a key!

Please let me know when their proposal will become available.

**Comment by maximbaz** [comment]
> > Badge background color will be configurable later on, we anyway need to support this to distinguish multiple stores wink
>
> GREAT!

@532910 to reward you for your feedback, I changed my priorities and went with implementing this for you now 😝: https://github.com/browserpass/browserpass-extension/pull/72

Sorry that I'm not agreeing with everything you say, but I hope you at least like the general trend 😉

**Comment by 532910** [comment]
> @532910 to reward you for your feedback, I changed my priorities and went with implementing this for you now stuck_out_tongue_closed_eyes: #72
Awesome!
 
> Sorry that I'm not agreeing with everything you say, but I hope you at least like the general trend wink

No worries, it's absolutely normal and there is @erayd for those thing you are not agree (:

And sure I'm like the general trend.

**Comment by erayd** [comment]
> No worries, it's absolutely normal and there is @erayd for those thing you are not agree (:.

I do actually agree with @maximbaz most of the time though ;-).
