### ISSUE TITLE
new layout

### ISSUE THREAD

**Issue by 532910** [browserpass/browserpass-extension#71]
Two cons for new layout:

1. A lot of unusable space (red outline on screenshot):
![image](https://user-images.githubusercontent.com/14617699/55674897-808b7180-58c3-11e9-8f4b-283bf51d30fb.png)

2. The line is significat ticker, so less passwors fits into list (only 7):
![image](https://user-images.githubusercontent.com/14617699/55674977-4ec6da80-58c4-11e9-81fa-930195006500.png)

What the pros are?

**Comment by maximbaz** [comment]
Pros: more readable, easier to quickly spot the the domain, and I like it 😄 

The goal is not to fit as many password entries or make popup as narrow as possible, but to make it simple for users to recognize the correct password entry with just a quick glance.

If there are many entries in the list, it is expected that you would use the search functionality to filter them out.
