### ISSUE TITLE
Can't work on Archlinux without browserpass-chromium installed

### ISSUE THREAD

**Issue by X1aomu** [browserpass/browserpass-extension#88]
I'm excited to see that the version 3 was released and I can't wait to try it out. But I have encountered some problems.

If I install the extension from the web store and install the native host from the pacman, it won't work. When I click the extension icon, there goes the wrong message:
`Error: Error: Specified native messaging host not found.`(yes, there are two 'Error's)

But if I install `browserpass-chromium` from pacman, then everything goes fine. And even I enable both of the two versions (one from the web store, one from the pacman) at the same time, they both work normally. However, if I uninstall the version installed from the pacman, (still with the native host installed) the version from web store cannot work along.

**Comment by maximbaz** [comment]
Hey, glad you are excited 🙂 

The reason for the behavior you see is that just like in v2, [a browser must be additionally configured](https://github.com/browserpass/browserpass-native#configure-browsers) to link browser extension and a native host. I did this as part of `browserpass-chromium/chrome/firefox` packages, but if you install it from Web store, you need to do this yourself.

Just to clarify, if you are on Arch, I highly recommend using extensions from the repo instead of from Web store, for two reasons: 

- The extensions in `[community]` are PGP signed by me, you don't need to trust that my Web store account hasn't been hacked.
- All `browserpass*` packages in `[community]` will be updated at the same time, meaning that you'll never experience breaking changes anymore.

**Comment by erayd** [comment]
@maximbaz Can you roll a `browserpass-webstore` package? That could install the host app config, and possibly chrome policy that forces it to install from the webstore. That way the `browserpass-chromium` package won't be required if the user does actually want the webstore version.

If `browserpass-native` is set to depend on _one* of `-chromium` or `-webstore`, then we can guarantee that anyone who installs the native app will have a working extension.

**Comment by maximbaz** [comment]
But I don't want Arch users to use webstore version, there's no good reason to do so, policy is for those distros that don't provide a dedicated package 😉 

`browserpass` has both `-chromium` and `-firefox` as optional depends, and judging by this issue @X1aomu didn't have any issues discovering the existence of a new `browserpass-chromium` package 🙂

**Comment by erayd** [comment]
Fair enough :-).

**Comment by X1aomu** [comment]
Thanks for the reply :smile: 

I've known the reasons after I glanced the file structure of thoes package. I just thought the package `browserpass` will do these stuffs (let the browsers know and launch the native app).

However, I still have some considerations. I not only work on Archlinux daily, but also other operating systems. Then if I use the distro's pakaged extension, the google sync service will not sync the extension for me on other platforms. For syncing, I have to keep and enable the webstore version. The cons is that I must keep and on two versions on Archlinux. That is why I preferred to install the extension from the webstore. And I also think that it's not a good way to make the package `browserpass` do the stuffs as there may be many browsers to fit.

Now I've figured out the best choice for me. That is, install both the two version, then keep the webstore version enabled and the other disabled. 

Though this way differs your hope, as actually I'm using the webstore version, I don't know if there's a better way.

**Comment by maximbaz** [comment]
Huh, good point, if you install an extension from Web store on another OS, Google will sync it into your Arch and you will anyway end up with two extensions, I haven't thought about it 🤔 

> And I also think that it's not a good way to make the package browserpass do the stuffs as there may be many browsers to fit.

Yeah, in the past I did get some pushback of bundling configs for all browsers in `browserpass` package itself, and I'm pretty sure I would get pushback for an official hypothetical package `browserpass-chrome-webstore` that would install a single symlink to a json file.

In cases like yours I would recommend you install `browserpass` package only, and manually configure the browser - it is as simple as running `sudo make -f /usr/lib/browserpass/Makefile hosts-chromium` or `make -f /usr/lib/browserpass/Makefile hosts-chromium-user`

**Comment by X1aomu** [comment]
Problem solved. Thank you all guys.
