### ISSUE TITLE
docs: why the required permissions

### ISSUE THREAD

**Issue by pimlie** [browserpass/browserpass-extension#93]
First thanks for all your work. My chromium browser just found the new v3.0.8 and upgraded the extension (:tada:) . This automatically disabled the extension because v3 requires some additional permissions.

In the light of full disclosure, could you maybe elaborate in the readme for which features these permissions are needed? Eg the main thing which is not immediately clear to me is why this extension now needs the permission `Modify data that you copy and paste`.

**Comment by maximbaz** [comment]
Very good idea, will do 👍 

To give you a quick answer, this is needed for "copy username" and "copy password" functionality that you can access via shortcuts or buttons in the popup.
